In [4]:
#!pip install numpy
#np.version.version
import numpy as np
a = np.array([[79,65,44,55], [65,66,78,66],[77,66,44,33]])
print(a)
print(np.amin(a))
print(np.amin(a, axis=1))
print(np.amin(a, axis=0))

[[79 65 44 55]
 [65 66 78 66]
 [77 66 44 33]]
33
[44 65 33]
[65 65 44 33]


In [5]:
print(np.median(a))
print(np.median(a,axis=1))
print(np.median(a,axis=0))

65.5
[60. 66. 55.]
[77. 66. 44. 55.]


In [6]:
a = np.array([1,2,3,4])
wts = np.array([4,3,2,1])
print(np.average(a))
print(np.mean(a))
print(np.average(a, weights=wts)) #weighted averge
np.var(a)
np.std(a)

2.5
2.5
2.0


1.118033988749895

In [7]:
a = np.array([[79,65,44,55], [65,66,78,66],[77,66,44,33]])
a

array([[79, 65, 44, 55],
       [65, 66, 78, 66],
       [77, 66, 44, 33]])

In [8]:
x=np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
print(np.sort(a))
print()
print(np.sort(a,axis=1))
print()
print(np.sort(a, axis=0))

[[44 55 65 79]
 [65 66 66 78]
 [33 44 66 77]]

[[44 55 65 79]
 [65 66 66 78]
 [33 44 66 77]]

[[65 65 44 33]
 [77 66 44 55]
 [79 66 78 66]]


In [10]:
x[np.where(x<3)]

array([0, 1, 2])

In [11]:
condition = np.mod(x,2)==0
np.extract(condition, x)

array([0, 2, 4, 6, 8])

In [12]:
sales = [4543,2233,4335,3344,4543,6544,3565,3344,6543,6644,8765,3323,5654,3344,5654,7766]
profit = [454,233,443,566,777,677,555,766,455,554,665,455,345,766,444,567]
len(sales)
len(profit)
profitratio = []
for i in range(0,len(sales)):
    profitratio.append(profit[i]/sales[i])
profitratio

[0.099933964340744,
 0.10434393193013883,
 0.10219146482122261,
 0.16925837320574164,
 0.17103235747303544,
 0.10345354523227383,
 0.15568022440392706,
 0.229066985645933,
 0.06953996637627999,
 0.08338350391330523,
 0.07586993725042784,
 0.13692446584411677,
 0.061018747789175806,
 0.229066985645933,
 0.07852847541563494,
 0.07301055884625289]

In [13]:
sales_array = np.array(sales)
profit_array = np.array(profit)
profit_array/sales_array

array([0.09993396, 0.10434393, 0.10219146, 0.16925837, 0.17103236,
       0.10345355, 0.15568022, 0.22906699, 0.06953997, 0.0833835 ,
       0.07586994, 0.13692447, 0.06101875, 0.22906699, 0.07852848,
       0.07301056])

In [14]:
import time 
start = time.time()
profitratio = []
for i in range(0,len(sales)):
    profitratio.append(profit[i]/sales[i])
profitratio
print((time.time() - start)*1000)

0.20432472229003906


In [15]:
size = 1000000
l1 = range(size)
l2 = range(size)
a1 = np.arange(size)
a2 = np.arange(size)

start = time.time()
result = [(x,y) for x,y in zip(l1,l2)]
print('Time taken by list operation')
print((time.time()-start)*1000)

start = time.time()
result = a1 + a2
print('Time taken by Array')
print((time.time()-start)*1000)

Time taken by list operation
290.6975746154785
Time taken by Array
54.02565002441406


In [16]:
cust  = ['A1', 'A2','A3','A4']
order = [1,2,3,4]
for (c,o) in zip(cust, order):
    print('Hello', c, 'Your order id is:', o)

Hello A1 Your order id is: 1
Hello A2 Your order id is: 2
Hello A3 Your order id is: 3
Hello A4 Your order id is: 4


In [17]:
list1 = [True]
type(list1[0])

bool

In [18]:
array1 = np.array(list1)
array1
type(array1[0])

numpy.bool_

In [19]:
list1 = [32,3,44,34,54]
list1*2

[32, 3, 44, 34, 54, 32, 3, 44, 34, 54]

In [20]:
array1 = np.array(list1)
array1*2

array([ 64,   6,  88,  68, 108])

In [21]:
list2 = list1.copy()
list3 = list1[0:3]
list3

[32, 3, 44]

In [22]:
a1 = np.array(list1)
a2 = a1.copy()
a2

array([32,  3, 44, 34, 54])

In [23]:
a3 = a1[0:3]
a3

array([32,  3, 44])

In [24]:
type(a3)

numpy.ndarray

In [25]:
a3.dtype

dtype('int64')

In [26]:
a1.ndim

1

In [27]:
a1.var

<function ndarray.var>

In [28]:
sales_us = [4354,3345,3432,2232]
sales_eu = [5433,3433,5554,3333]
sales_jp = [2222,3242,2223,3322]

profit_us = [435,444,545,566]
profit_eu = [544,234,534,566]
profit_jp = [655,554,334,454]

In [29]:
sales_matrix = np.array([sales_us,sales_eu,sales_jp])
profit_matrix = np.array([profit_us, profit_eu, profit_jp])
sales_matrix.shape

(3, 4)

In [30]:
profit_matrix/sales_matrix

array([[0.09990813, 0.13273543, 0.15879953, 0.25358423],
       [0.10012884, 0.06816196, 0.09614692, 0.16981698],
       [0.29477948, 0.17088217, 0.15024741, 0.13666466]])

In [31]:
type(profit_matrix)
#profit_matrix.ndim

numpy.ndarray

In [32]:
profit_matrix#[1,2]

array([[435, 444, 545, 566],
       [544, 234, 534, 566],
       [655, 554, 334, 454]])

In [33]:
profit_matrix[:, 2:4]

array([[545, 566],
       [534, 566],
       [334, 454]])

In [34]:
profit_matrix[0][2]
profit_matrix[0,2]

545

In [35]:
rdict = {'US':0, 'EU':1, 'JP':2}
qdict = {'Q1':0, 'Q2':1, 'Q3':2, 'Q4':3}
profit_matrix[rdict['US']][qdict['Q3']]

545

In [36]:
a = np.arange(1,25)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [37]:
a.reshape(2,3,4)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [38]:
stu_details = {'st_id':[1,2,3,4,5], 
              'stu_name':['A','B','C','D','E'],
              'Region':['N','S','W','E','S']}

stu_marks = {'st_id':[1,2,3,4,6],
            'sub':['Py','Tab','R','Py','Py'],
            'Marks':[35,32,34,37,38]}

In [39]:
import pandas as pd
pd.__version__

'1.1.5'

In [40]:
stu_details = pd.DataFrame(stu_details)
stu_marks = pd.DataFrame(stu_marks)
pd.merge(stu_details,stu_marks, on='st_id', how='inner')

st_id stu_name Region  sub  Marks
0      1        A      N   Py     35
1      2        B      S  Tab     32
2      3        C      W    R     34
3      4        D      E   Py     37

In [41]:
stu_details

st_id stu_name Region
0      1        A      N
1      2        B      S
2      3        C      W
3      4        D      E
4      5        E      S

In [42]:
stu_marks

st_id  sub  Marks
0      1   Py     35
1      2  Tab     32
2      3    R     34
3      4   Py     37
4      6   Py     38

In [43]:
pd.merge(stu_details,stu_marks, on='st_id', how='left')

st_id stu_name Region  sub  Marks
0      1        A      N   Py   35.0
1      2        B      S  Tab   32.0
2      3        C      W    R   34.0
3      4        D      E   Py   37.0
4      5        E      S  NaN    NaN

In [44]:
pd.merge(stu_details,stu_marks, on='st_id', how='right')

st_id stu_name Region  sub  Marks
0      1        A      N   Py     35
1      2        B      S  Tab     32
2      3        C      W    R     34
3      4        D      E   Py     37
4      6      NaN    NaN   Py     38

In [45]:
pd.merge(stu_details,stu_marks, on='st_id', how='outer')

st_id stu_name Region  sub  Marks
0      1        A      N   Py   35.0
1      2        B      S  Tab   32.0
2      3        C      W    R   34.0
3      4        D      E   Py   37.0
4      5        E      S  NaN    NaN
5      6      NaN    NaN   Py   38.0

In [46]:
stu_details_Nag = {'st_id':[1,2,3,4,5,6],
                  'stu_name':['A','B','C','D','E','F'],
                  'sub':['Py','Tab','Py','Tab','PY','k']}

stu_details_US = {'st_id':[6,7,8,9,10],
                  'stu_name':['T','Y','U','I','O'],
                  'sub':['Tab','Tab','Tab','SQL','PY']}

In [47]:
stu_details_Nag=pd.DataFrame(stu_details_Nag)
stu_details_US=pd.DataFrame(stu_details_US)

In [48]:
student_details = pd.concat([stu_details_Nag, stu_details_US],axis=0)#1
student_details

st_id stu_name  sub
0      1        A   Py
1      2        B  Tab
2      3        C   Py
3      4        D  Tab
4      5        E   PY
5      6        F    k
0      6        T  Tab
1      7        Y  Tab
2      8        U  Tab
3      9        I  SQL
4     10        O   PY