In [ ]:
edureka!
AI-ML
Question Bank 1
Electronics & ICT Academy
National Institute of Technology, Warangal
Post Graduate Diploma

In [ ]:
import re 
 
s=input("Enter text: ") 
lst = re.findall('\S+@[a-z]+.com$', s) 
print(lst) 

Enter text: 'kjfhvkjh@bkc.com, hdvch@vhshxh.com'
[]


In [ ]:
def make_account():
    return {'balance': 0}
def deposit(accounte, amount):
    accounte['balance'] += amount
    print("Deopsit Balance:",accounte['balance'])
    return accounte['balance']
def withdraw(accounte, amount):
    accounte['balance'] -= amount
    print("Withdrawal Balance: ",accounte['balance'])
    return accounte['balance']
Aashi=make_account()
amt=int(input("Enter amount to be deposited or withdrawn: "))
deposit(Aashi,amt)
amt=int(input("Enter amount to be deposited or withdrawn: "))
withdraw(Aashi,amt)

Enter amount to be deposited or withdrawn: 10000
Deopsit Balance: 10000
Enter amount to be deposited or withdrawn: 500
Withdrawal Balance:  9500


9500

In [ ]:
Aashi

{'balance': 9500}

In [ ]:
import datetime
 
def numOfDays(date1, date2): 
    return (date2-date1).days
 
date1_ent = input('Enter a date in YYYY-MM-DD format: ')
year, month, day = map(int, date1_ent.split('-'))
date1 = datetime.date(year, month, day)
date2_ent = input('Enter a date in YYYY-MM-DD format: ')
year, month, day = map(int, date2_ent.split('-'))
date2 = datetime.date(year, month, day) 
print(numOfDays(date1, date2), "days")

Enter a date in YYYY-MM-DD format: 2000-09-08
Enter a date in YYYY-MM-DD format: 2009-07-12
3229 days


In [ ]:
date1

datetime.date(2000, 9, 8)

In [ ]:
l=list(string.ascii_uppercase + string.ascii_lowercase  + string.digits)
string.ascii_letters


'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'

In [ ]:
pw='$'.join(l)
pw

'A$B$C$D$E$F$G$H$I$J$K$L$M$N$O$P$Q$R$S$T$U$V$W$X$Y$Z$a$b$c$d$e$f$g$h$i$j$k$l$m$n$o$p$q$r$s$t$u$v$w$x$y$z$0$1$2$3$4$5$6$7$8$9'

In [ ]:
import string,random
passw=''
n=int(input("Enter length of password: "))
for i in range(n):
    passw= passw + random.choice(string.ascii_uppercase + string.ascii_lowercase + string.digits)
print(passw)

Enter length of password: 6
Eq7zy3


In [ ]:
import re

def password():
    print ('Enter a password\n\nThe password must be between 6 and 12 characters.\n')
    while True:

        password = input('Password: ')
        if 6 <= len(password) < 12:
            break
        
        print ('Invalid - Re-Enter\n')

    password_scores = {0:'Horrible', 1:'Weak', 2:'Medium', 3:'Strong'}
    password_strength = dict.fromkeys(['has_upper', 'has_lower', 'has_num'], False)

    if re.search(r'[A-Z]', password):
        password_strength['has_upper'] = True

    if re.search(r'[a-z]', password):
        password_strength['has_lower'] = True

    if re.search(r'[0-9]', password):
        password_strength['has_num'] = True

    score = len([Tru for Tru in password_strength.values() if Tru])
    print ('Password is %s' % password_scores[score])
password()

Enter a password

The password must be between 6 and 12 characters.

Password: cdsa3
Invalid - Re-Enter

Password: hgiuyuuiou
Password is Weak


In [ ]:
import math
def sqrfunc(n):
    return lambda n:n*n
def cubefunc(n):
    return lambda n:n*n*n
def sqrtfunc(n):
    return lambda n: math.sqrt(n)
n= int(input("Enter a number: "))
sqr = sqrfunc(n)
cube= cubefunc(n)
sqrrt=sqrtfunc(n)
print("Square: ",sqr)
print("Cube: ",cube(n))
print("Square Root: ",sqrrt(n))
sqr(7)

Enter a number: 78
Square:  <function sqrfunc.<locals>.<lambda> at 0x0000021EC021DF70>
Cube:  474552
Square Root:  8.831760866327848


49

In [ ]:
import math
def sqrfunc(n):
    return n*n
def cubefunc(n):
    return lambda n:n*n*n
def sqrtfunc(n):
    return lambda n: math.sqrt(n)
n= int(input("Enter a number: "))
sqr = sqrfunc(n)
# cube= cubefunc(n)
# sqrrt=sqrtfunc(n)
# print("Square: ",sqr)
# print("Cube: ",cube(n))
# print("Square Root: ",sqrrt(n))
sqr

Enter a number: 76


5776

In [ ]:
import math
#formulas for each geometric figure
def calc_square(a_side):
    square_area = a_side ** 2
    return square_area
def calc_rectangle(w_side, l_side):
    rect_area = l_side * w_side
    return rect_area
def calc_triangle(base, height):
    triangle_area = (base * height) / 2
    return triangle_area
def calc_circle(radius):
    circle_area = math.pi * radius ** 2
    return circle_area
def calc_trapezoid(short_base, long_base, height):
    trapezoid_area = ((short_base + long_base) / 2 ) * height
    return trapezoid_area

#function determining which formula to calculate
def area_calc_logic(user_calc):
    if user_calc == "square":
        a_side = float(input("Give length of side: "))
        print("Area: ",calc_square(a_side))
    elif user_calc == "rectangle":
        l_side = float(input("Give the length: "))
        w_side = float(input("Give the width: "))
        print("Area: ",calc_rectangle(w_side, l_side))
    elif user_calc == "triangle":
        base = float(input("Give the length of base: "))
        height = float(input("Give the height: "))
        print("Area: ",calc_triangle(base, height))
    elif user_calc == "circle":
        radius = float(input("Give the radius: "))
        print("Area: ",calc_circle(radius))
    elif user_calc == "trapezoid":
        short_base = float(input("Give the length of the short base: "))
        long_base = float(input("Give the length of the long base: "))
        height = float(input("Give the height: "))
        print("Area: ",calc_trapezoid(short_base, long_base, height))
    else:
        area_calc_logic(input("Error, Re-enter input: "))


# if __name__ == '__main__': #?????
    
#     print("This program will calculate/narea of some geometric shapes for you")
#     print( "Enter Square, Rectangle, Triangle, Circle, or Trapezoid")
#     shape=(input("What area would you like to calculate? ")).lower()
#     area_calc_logic(shape)

In [ ]:
print("This program will calculate/narea of some geometric shapes for you")
print( "Enter Square, Rectangle, Triangle, Circle, or Trapezoid")
shape=(input("What area would you like to calculate? ")).lower()
area_calc_logic(shape)

This program will calculate/narea of some geometric shapes for you
Enter Square, Rectangle, Triangle, Circle, or Trapezoid
What area would you like to calculate? square
Give length of side: 78
Area:  6084.0


In [ ]:
try:
    a = int(input("Enter numerator number: "))
    b = int(input("Enter denominator number: "))
    print("Result of Division: " + str(a/b))
except(ZeroDivisionError):
    print("You have divided a number by zero, which is not allowed.")
except(ValueError):
    print("You must enter integer value")
except:
    print("Oops! Something went wrong!")

Enter numerator number: 5
Enter denominator number: 0
You have divided a number by zero, which is not allowed.


In [ ]:
try:
    a = int(input("Enter numerator number: "))
    b = int(input("Enter denominator number: "))
    print("Result of Division: " + str(a/b))
except Exception as e:
    print("You have divided a number by zero, which is not allowed.")
    print(e)
except(ValueError):
    print("You must enter integer value")
except:
    print("Oops! Something went wrong!")

In [3]:
# 10. Write a python program to check for a file in the current directory.
# Hint: Use custom exceptions.
import os
class Error(Exception): # not clear
    """Base class for other exceptions"""
    pass
class FileNotPresent(Error):#class FileNotPresent(Exception): also gives same result whats difference? 
    """Base class for other exceptions"""
    pass

def find_all(name, path):
    try:
        result = []
        for root, dirs, files in os.walk(path):
            if name in files:
                result.append(os.path.join(root, name))
            # else:
            #     raise FileNotPresent
                return result

    except FileNotPresent:
        print("File NOT @@ present")
 
fname = input("Enter the file name: ")
fpath = input("Enter path to search: ")
find_all(fname,fpath)

Enter the file name: anscombe.json
Enter path to search: /content


['/content/sample_data/anscombe.json']

In [ ]:
import os
class Error(Exception):
    """Base class for other exceptions"""
    pass
class FileNotPresent(Error):
    """Base class for other exceptions"""
    pass
try:
    def find_all(name, path):
        result = []
        for root, dirs, files in os.walk(path):
            if name in files:
                result.append(os.path.join(root, name))
            
            #raise FileNotPresent
        return result

except(FileNotPresent):
    print("File NOT present")

In [ ]:
fname = input("Enter the file name: ")
fpath = input("Enter path to search: ")
find_all(fname,fpath)

Enter the file name: 'prime.txt'
Enter path to search: 'C:\\Users\\Dell\\Desktop\\MyPractice Colab\\Python PROGRAMS'


[]

In [ ]:
def find_all(name, path):
    result = []
    for root, dirs, files in os.walk(path):
        if name in files:
            result.append(os.path.join(root, name))
        else:
            print('FileNotPresent')
    return result



find_all('prime.txt','C:\\Users\\Dell\\Desktop\\MyPractice Colab\\Python PROGRAMS')

FileNotPresent
FileNotPresent
FileNotPresent
FileNotPresent
FileNotPresent
FileNotPresent
FileNotPresent


['C:\\Users\\Dell\\Desktop\\MyPractice Colab\\Python PROGRAMS\\PythonBasics\\prime.txt']

In [ ]:
os.getcwd()

'C:\\Users\\Dell\\Desktop\\PyRahulTiwari\\PythonPROGRAMS\\PythonBasics'

In [ ]:
# 12. Write a Python function to find the Max of three numbers.
def max_of_two( x, y ):
    if x > y:
        return x
    return y
def max_of_three( x, y, z ):
    return max_of_two( x, max_of_two( y, z ) )

n= int(input("Enter no. of digits to compare: "))
if n==2:
    x=int(input("Enter first number: "))
    y=int(input("Enter second number: "))
    print(max_of_two(x,y))

elif n==3:
    x=int(input("Enter first number: "))
    y=int(input("Enter second number: "))
    z=int(input("Enter third number: "))
    print(max_of_three(x,y,z))
else:
    print("Enter N : 2 or 3")

Enter no. of digits to compare: 3
Enter first number: 1
Enter second number: 2
Enter third number: 3
3


In [ ]:
# 11. Write a python code to match all MAC addressesngiven in the input.
import re
mac= input("Enter a MAC address: ")
if re.search("^[a-fA-F0-9:]{17}|[a-fA-F0-9]{12}$", mac):
    print("Valid MAC address")
else:
    print("Not valid address")

Enter a MAC address: ABC:abc:123:ABC:8
Valid MAC address


In [ ]:
#14. Write a Python function to check whether a string is a pangram or not? The quick brown fox jumps over the lazy dog
import string, sys
def ispangram(str1, alphabet=string.ascii_lowercase):
    alphaset = set(alphabet)
    print(alphaset)
    print(set(str1.lower()))
    return alphaset <= set(str1.lower())

pan=input("Enter a sentence: ")
print (ispangram(pan))

Enter a sentence: The quick brown fox jumps over the lazy dog
{'t', 'y', 'x', 'v', 'a', 'p', 'b', 'o', 'e', 'q', 's', 'u', 'c', 'w', 'z', 'r', 'h', 'm', 'n', 'f', 'g', 'i', 'l', 'j', 'd', 'k'}
{'t', 'y', 'x', 'v', 'a', 'p', 'b', 'o', 'e', 'q', 's', 'u', 'c', 'w', 'z', 'r', 'h', 'm', 'n', 'f', 'g', ' ', 'i', 'l', 'j', 'd', 'k'}
True


In [ ]:
string.ascii_lowercase

'abcdefghijklmnopqrstuvwxyz'

In [ ]:
#15. Write a Python class to convert an integer to a roman numeral.
class py_Roman:
    def int_to_Roman(self, num):
        val = [1000, 900, 500, 400, 100, 90, 50, 40, 10, 9, 5, 4, 1]
        syb = ["M", "CM", "D", "CD", "C", "XC", "L", "XL", "X", "IX", "V", "IV", "I" ]
        roman_num = ''
        i = 0
        while num > 0:
            for j in range(num // val[i]):
                roman_num += syb[i]
                num -= val[i]
            i += 1
        return roman_num

num= int(input("Enter a number: "))
print("Roman numeral: ",py_Roman().int_to_Roman(num))

Enter a number: 2345
Roman numeral:  MMCCCXLV


In [ ]:
# 16. Write a Python class to find a pair of elements(indices of the two numbers) from a given array whose sum equals a specific target number.
# Input: numbers= [10,20,10,40,50,60,70], target=90
# Output: index1 = 3; index2 = 4
class py_solution:
    def twoSum(self, nums, target):
        lookup = {}
        print(lookup)
        for i, num in enumerate(nums):
            print(i,num)
            #print(lookup[target - num])
            if target - num in lookup:
                print(lookup[target - num], i )
                return (lookup[target - num], i )
            lookup[num] = i
            print(lookup)
target=int(input("Enter target sum: ")) 
print("index1=%d, index2=%d" % py_solution().twoSum((10,20,10,40,50,60,70),target))

Enter target sum: 90
{}
0 10
{10: 0}
1 20
{10: 0, 20: 1}
2 10
{10: 2, 20: 1}
3 40
{10: 2, 20: 1, 40: 3}
4 50
3 4
index1=3, index2=4


In [ ]:
l =  [10,20,10,40,50,60,70]
n = int(input())
for i in l:
    if n-i in l:
        print(i,n-i)
        print(l.index(i),l.index(n-i))
        


90
20 70
1 6
40 50
3 4
50 40
4 3
70 20
6 1


In [ ]:
a=enumerate((10,20,10,40,50,60,70))
type(a)

enumerate

In [ ]:
# 17. Write a Python program to get the class name of an instance in Python.
inst=input("Enter instance: ")
inst.__class__.__name__

Enter instance: '1'


'str'

In [ ]:
# 18. Write a Python program to calculate the Discriminant value of a quadratic equation
def discriminant():
    a_value = float(input('The a value: '))
    b_value = float(input('The b value: '))
    c_value = float(input('The c value: '))
    discriminant = (b_value**2) - (4*a_value*c_value)
    if discriminant > 0:
        print('Two Solutions. Discriminant value is:', discriminant)
    elif discriminant == 0:
        print('One Solution. Discriminant value is:', discriminant)
    elif discriminant < 0:
        print('No Real Solutions. Discriminant value is:', discriminant)
discriminant()

The x value: 2
The y value: 3
The z value: 4
No Real Solutions. Discriminant value is: -23.0


In [ ]:
# 19.
def abc():
    x = 1
    y = 2
    str1= "This is a test example."
    print("Python Exercises")
print(abc.__code__.co_nlocals)

3


In [ ]:
# 20.
import os, time
def last_modified_fileinfo(filepath):
    filestat = os.stat(filepath)
    date = time.localtime((filestat.st_mtime))
    print(date)
# Extract year, month and day from the date
    year = date[0]
    month = date[1]
    day = date[2]
 # Extract hour, minute, second
    hour = date[3]
    minute = date[4]
    second = date[5]
 # Year
    strYear = str(year)[0:]
 # Month
    if (month <=9):
        strMonth = '0' + str(month)
    else:
        strMonth = str(month)
 # Date
    if (day <=9):
        strDay = '0' + str(day)
    else:
        strDay = str(day)
    print()
    return (strYear+"-"+strMonth+"-"+strDay+" "+str(hour)+":"+str(minute)+":"+str(second))

print(last_modified_fileinfo('prime.txt'))
# Enter a file present in the same folder, else mention the absolute path.
print()


time.struct_time(tm_year=2021, tm_mon=6, tm_mday=17, tm_hour=17, tm_min=27, tm_sec=57, tm_wday=3, tm_yday=168, tm_isdst=0)

2021-06-17 17:27:57



In [ ]:
print(calendar.TextCalendar(calendar.SUNDAY).formatyear(2022,1,1,1,3))

                              2022

      January               February               March
Su Mo Tu We Th Fr Sa  Su Mo Tu We Th Fr Sa  Su Mo Tu We Th Fr Sa
                   1         1  2  3  4  5         1  2  3  4  5
 2  3  4  5  6  7  8   6  7  8  9 10 11 12   6  7  8  9 10 11 12
 9 10 11 12 13 14 15  13 14 15 16 17 18 19  13 14 15 16 17 18 19
16 17 18 19 20 21 22  20 21 22 23 24 25 26  20 21 22 23 24 25 26
23 24 25 26 27 28 29  27 28                 27 28 29 30 31
30 31

       April                  May                   June
Su Mo Tu We Th Fr Sa  Su Mo Tu We Th Fr Sa  Su Mo Tu We Th Fr Sa
                1  2   1  2  3  4  5  6  7            1  2  3  4
 3  4  5  6  7  8  9   8  9 10 11 12 13 14   5  6  7  8  9 10 11
10 11 12 13 14 15 16  15 16 17 18 19 20 21  12 13 14 15 16 17 18
17 18 19 20 21 22 23  22 23 24 25 26 27 28  19 20 21 22 23 24 25
24 25 26 27 28 29 30  29 30 31              26 27 28 29 30

        July                 August              September
Su Mo Tu We Th 

In [ ]:
# 21.
import calendar
cal = calendar.TextCalendar(calendar.SUNDAY)
# column width: 2, lines per week: 1 
# number of spaces between month columns: 1
# 3: no. of months per column.
year=int(input("Enter the year: "))
print(cal.formatyear(year, 1, 1, 1, 4))

Enter the year: 2000
                                         2000

      January               February               March                 April
Su Mo Tu We Th Fr Sa  Su Mo Tu We Th Fr Sa  Su Mo Tu We Th Fr Sa  Su Mo Tu We Th Fr Sa
                   1         1  2  3  4  5            1  2  3  4                     1
 2  3  4  5  6  7  8   6  7  8  9 10 11 12   5  6  7  8  9 10 11   2  3  4  5  6  7  8
 9 10 11 12 13 14 15  13 14 15 16 17 18 19  12 13 14 15 16 17 18   9 10 11 12 13 14 15
16 17 18 19 20 21 22  20 21 22 23 24 25 26  19 20 21 22 23 24 25  16 17 18 19 20 21 22
23 24 25 26 27 28 29  27 28 29              26 27 28 29 30 31     23 24 25 26 27 28 29
30 31                                                             30

        May                   June                  July                 August
Su Mo Tu We Th Fr Sa  Su Mo Tu We Th Fr Sa  Su Mo Tu We Th Fr Sa  Su Mo Tu We Th Fr Sa
    1  2  3  4  5  6               1  2  3                     1         1  2  3  4  5
 7  8  

In [ ]:
# 22. Python Program to print all permutations of a given string.
def toString(List): 
    return ''.join(List) 
# Function to print permutations of string 
# This function takes three parameters: 
# 1. String 
# 2. Starting index of the string 
# 3. Ending index of the string. 
def permute(a, l, r): 
    if l == r: 
        #pass
        print(toString(a)) 
    else: 
        for i in range(l, r + 1): 
            a[l], a[i] = a[i], a[l] 
            print('list 1: l i',a,l,i)
            permute(a, l + 1, r) 
            a[l], a[i] = a[i], a[l] # backtrack 
            print('list 2:l i',a,l,i)
 
string = input("Enter a string: ")
n = len(string) 
a = list(string) 
permute(a, 0, n-1) 

Enter a string: ABC
list 1: l i ['A', 'B', 'C'] 0 0
list 1: l i ['A', 'B', 'C'] 1 1
ABC
list 2:l i ['A', 'B', 'C'] 1 1
list 1: l i ['A', 'C', 'B'] 1 2
ACB
list 2:l i ['A', 'B', 'C'] 1 2
list 2:l i ['A', 'B', 'C'] 0 0
list 1: l i ['B', 'A', 'C'] 0 1
list 1: l i ['B', 'A', 'C'] 1 1
BAC
list 2:l i ['B', 'A', 'C'] 1 1
list 1: l i ['B', 'C', 'A'] 1 2
BCA
list 2:l i ['B', 'A', 'C'] 1 2
list 2:l i ['A', 'B', 'C'] 0 1
list 1: l i ['C', 'B', 'A'] 0 2
list 1: l i ['C', 'B', 'A'] 1 1
CBA
list 2:l i ['C', 'B', 'A'] 1 1
list 1: l i ['C', 'A', 'B'] 1 2
CAB
list 2:l i ['C', 'B', 'A'] 1 2
list 2:l i ['A', 'B', 'C'] 0 2


In [ ]:
# 23. Write Pythonic code to simulate distribution of a deck of cards.
rs = [[rank , suit] for rank in "A23456789TJQK" for suit in "CDHS"]
rs

[['A', 'C'],
 ['A', 'D'],
 ['A', 'H'],
 ['A', 'S'],
 ['2', 'C'],
 ['2', 'D'],
 ['2', 'H'],
 ['2', 'S'],
 ['3', 'C'],
 ['3', 'D'],
 ['3', 'H'],
 ['3', 'S'],
 ['4', 'C'],
 ['4', 'D'],
 ['4', 'H'],
 ['4', 'S'],
 ['5', 'C'],
 ['5', 'D'],
 ['5', 'H'],
 ['5', 'S'],
 ['6', 'C'],
 ['6', 'D'],
 ['6', 'H'],
 ['6', 'S'],
 ['7', 'C'],
 ['7', 'D'],
 ['7', 'H'],
 ['7', 'S'],
 ['8', 'C'],
 ['8', 'D'],
 ['8', 'H'],
 ['8', 'S'],
 ['9', 'C'],
 ['9', 'D'],
 ['9', 'H'],
 ['9', 'S'],
 ['T', 'C'],
 ['T', 'D'],
 ['T', 'H'],
 ['T', 'S'],
 ['J', 'C'],
 ['J', 'D'],
 ['J', 'H'],
 ['J', 'S'],
 ['Q', 'C'],
 ['Q', 'D'],
 ['Q', 'H'],
 ['Q', 'S'],
 ['K', 'C'],
 ['K', 'D'],
 ['K', 'H'],
 ['K', 'S']]

In [ ]:
rs = [rank + suit for rank in "A23456789TJQK" for suit in "CDHS"]
rs

['AC',
 'AD',
 'AH',
 'AS',
 '2C',
 '2D',
 '2H',
 '2S',
 '3C',
 '3D',
 '3H',
 '3S',
 '4C',
 '4D',
 '4H',
 '4S',
 '5C',
 '5D',
 '5H',
 '5S',
 '6C',
 '6D',
 '6H',
 '6S',
 '7C',
 '7D',
 '7H',
 '7S',
 '8C',
 '8D',
 '8H',
 '8S',
 '9C',
 '9D',
 '9H',
 '9S',
 'TC',
 'TD',
 'TH',
 'TS',
 'JC',
 'JD',
 'JH',
 'JS',
 'QC',
 'QD',
 'QH',
 'QS',
 'KC',
 'KD',
 'KH',
 'KS']

In [ ]:
# 23. Write Pythonic code to simulate distribution of a deck of cards.
import random
def new_deck():
#  """
#  create a deck of cards
#  suit: club=C, diamond=D, heart=H spade=S
#  rank: ace=A, 10=T, jack=J, queen=Q, king=K, numbers=2..9
#  ace of spade would be AS, 8 of heart would be 8H and so on
#  return a list of a full deck of cards
#  """
    rs = [rank + suit for rank in "A23456789TJQK" for suit in "CDHS"]
    return rs
def draw_cards(n, cards_list):
#  """
#  randomly draw n cards from the deck (cards_list)
#  remove those cards from the deck
#  since object cards_list is by reference, it will change too
#  return a list of n cards
#  """
    random.shuffle(cards_list)
    return [cards_list.pop() for k in range(n)]
# new deck
cards_list = new_deck()
print("New deck = %s cards" % len(cards_list)) # test
# draw n cards per hand
n = 5
# draw the hands
hand1 = draw_cards(n, cards_list)
hand2 = draw_cards(n, cards_list)
print('-'*40)
# show the 2 hands
print("hand1 = %s" % hand1)
print("hand2 = %s" % hand2)
print('-'*40)
print("New deck = %s cards" % len(cards_list)) # test

New deck = 52 cards
----------------------------------------
hand1 = ['8C', '8S', 'QS', 'AD', '4H']
hand2 = ['JD', '2S', '6S', '8H', '2D']
----------------------------------------
New deck = 42 cards


In [ ]:
type(cards_list)

list

In [ ]:
# 24. Write a pythonic method which can calculate squar
class Square:
    def square(num):
        return num ** 2
n=int(input("Enter number: ")) 
sq=Square.square(n)
print("Square of number is: ",sq)

Enter number: 4
Square of number is:  16


In [ ]:
class Square():
    def square(num):
        return num ** 2
n=int(input("Enter number: ")) 
sq=Square
sq.square(n)
#print("Square of number is: ",sq)

Enter number: 6


36

In [ ]:
#25. Write a program to show the concept of polymorphism
class India(): 
    def capital(self): 
        print("New Delhi is the capital of India.") 
 
    def language(self): 
        print("Hindi the primary language of India.") 
 
    def Type(self): 
        print("India is a developing country.") 
        print()
 
class USA(): 
    def capital(self): 
        print("Washington, D.C. is the capital of USA.") 

    def language(self): 
        print("English is the primary language of USA.") 

    def Type(self): 
        print("USA is a developed country.") 
        print()
 
def func(obj): 
    obj.capital() 
    obj.language() 
    obj.Type() 
 
obj_ind = India()
obj_usa = USA() 
 
func(obj_ind) 
func(obj_usa) 

New Delhi is the capital of India.
Hindi the primary language of India.
India is a developing country.

Washington, D.C. is the capital of USA.
English is the primary language of USA.
USA is a developed country.



In [ ]:
# 26. Create a Python program of a Magic 8 Ball which is a toy used for fortune-telling.
import random
answers = ['It is certain', 'It is decidedly so', 'Without a doubt', 'Yes – definitely']
print('Hello World, I am the Magic 8 Ball, What is your name?')
name = input()
print('Hello ' + name)

def Magic8Ball():
    print('Ask me a question.')
    input()
    print (answers[random.randint(0, len(answers)-1)] )
    print('I hope that helped!')
    Replay()
 
def Replay():
    print ('Do you have another question? [Y/N] ')
    reply = input()
    if reply == 'Y':
        Magic8Ball()
    elif reply == 'N':
        print("Adios!")
        exit()
    else:
        print('I apologies, I did not catch that. Please repeat.')
        Replay()
Magic8Ball()

Hello World, I am the Magic 8 Ball, What is your name?
GD
Hello GD
Ask me a question.
How R U?
It is decidedly so
I hope that helped!
Do you have another question? [Y/N] 
Y
Ask me a question.
hOW DO U DO
Yes – definitely
I hope that helped!
Do you have another question? [Y/N] 
N
Adios!


In [ ]:
# 27. Write a Python program to find whether it contains an additive sequence or not
class Solution(object): # To Study
# DFS: iterative implement.
    def is_additive_number(self, num):
        length = len(num)
        for i in range(1, int(length/2+1)):
            for j in range(1, int((length-i)/2 + 1)):
                first, second, others = num[:i], num[i:i+j], num[i+j:]
                if self.isValid(first, second, others):
                    return True
        return False
    def isValid(self, first, second, others):
        if ((len(first) > 1 and first[0] == "0") or (len(second) > 1 and second[0] == "0")):
            return False
        sum_str = "%s"%(int(first) + int(second))
        if sum_str == others:
            return True
        elif others.startswith(sum_str):
            return self.isValid(second, sum_str, others[len(sum_str):])
        else:
            return False
if __name__ == "__main__":
    seq=input("Enter Sequence: ")
print(Solution().is_additive_number(seq))

Enter Sequence: 100200300500
True


In [ ]:
import string
b = '5'
a = int(b)
a = 5

# c = str(a)
# c

In [ ]:
num = 10

# check and print type of num variable
print(type(num))

# convert the num into string and print
converted_num = "% s" % num
print(type(converted_num))



<class 'int'>
<class 'str'>


In [ ]:
#Fibonnacci Series 0, 1, 1, 2, 3, 5, 8 ....

sq=input("Enter Sequence: ")
length = len(sq)
flag = False
for i in range(1, int(length/2+1)):
    for j in range(1, int((length-i)/2 + 1)):
        a, b = sq[:i], sq[i:i+j]
        print(a,b)
        str1 = sq[:i+j]
#         print(str1)
        x = length
#         print(x)
        while x:
            c = int(a) + int(b)
            a = int(b)
            b = int(c)
            c1 = "%s"% c
#             print(c1)
            str1 = str1+c1
            x = x-1
            if sq == str1:
                print(str1)
                flag = True
                break
               
        if len(sq) == len(str1):
            break
#         print(str1)
#         print()
if flag == False:
    print('No Match')

Enter Sequence: 0112358
0 1
0112358
01 1
0112358
011 2
011 23


In [ ]:
str1

'96659719761947292348707793'

In [ ]:
#Fibonnacci Series 0, 1, 1, 2, 3, 5, 8 ....
x = int(input('Enter the end Number:'))-2
sq=input("Enter Sequence: ")
a = int(sq[0:2])
b = int(sq[2:4])
str1=sq[0:4]
# print(a, b,end=' ')
while x:
    c = a + b
    a = b
    b = c
    c1 = "%s"% c
    str1 = str1+c1
    x = x-1
    if len(sq) == len(str1):
        break
print(str1)

Enter the end Number:11
Enter Sequence: 10122234
10122234


In [ ]:
#29. Develop a Pythonic code to demonstrate the concept of Abstraction. To Study
class employee:
    num_employee=0
    raise_amount=1.04
    def __init__(self, first, last, sal):
        self.first=first
        self.last=last
        self.sal=sal
        self.email=first + '.' + last + '@company.com'
        employee.num_employee+=1
    def fullname (self):
        return '{} {}'.format(self.first, self.last)
    def apply_raise (self):
        self.sal=int(self.sal* raise_amount)

class developer(employee):
    raise_amount = 1.10
    def __init__(self, first, last, sal, prog_lang):
        super().__init__(first, last, sal)
        self.prog_lang=prog_lang
 
class sales(employee):
    raise_amount = 1.01
    def __init__(self, first, last, sal, course_assign):
        super().__init__(first, last, sal)
        self.course_assign=course_assign
emp_1=developer('Guido', 'van Rossum', 1000000, 'Python')
emp_2=developer('Ani', 'Sri', 10000, 'Hadoop')
print(emp_1.prog_lang)
print(emp_2.sal)
print(emp_2.fullname)

Python
10000
<bound method employee.fullname of <__main__.developer object at 0x000001F3A68489D0>>


In [ ]:
class employee:
    num_employee=0
    raise_amount=1.04
    def __init__(self, first, last, sal):
        self.first=first
        self.last=last
        self.sal=sal
        self.email=first + '.' + last + '@company.com'
        employee.num_employee+=1
    def fullname (self):
        print(self.first+self.last)
        return '{} {}'.format(self.first, self.last)
    def apply_raise (self):
#         raise_amount=1.04
        self.sal=int(self.sal*employee.raise_amount)
        print(self.sal)

class developer(employee):
    raise_amount = 1.10
    def __init__(self, first, last, sal, prog_lang):
        super().__init__(first, last, sal)
        self.prog_lang=prog_lang
 
class sales(employee):
    raise_amount = 1.01
    def __init__(self, first, last, sal, course_assign):
        super().__init__(first, last, sal)
        self.course_assign=course_assign
emp_1=developer('Guido', 'van Rossum', 1000000, 'Python')
emp_2=developer('Ani', 'Sri', 10000, 'Hadoop')
print(emp_1.prog_lang)
print(emp_2.sal)
emp_2.fullname()
print(emp_2.email)
emp_2.apply_raise()



Python
10000
AniSri
Ani.Sri@company.com
10400


In [ ]:
emp_1.apply_raise()

1040000


In [ ]:
emp_2.sal

10400

In [ ]:
emp_3= sales('Guo', 'Roassum', 80000, 'MKTG')
emp_3.course_assign

'MKTG'

In [ ]:
emp_3.apply_raise()

83200


In [ ]:
emp_3.fullname()

GuoRoassum


'Guo Roassum'

In [ ]:
from abc import ABC, abstractmethod# Not Clear
class Polygon(ABC): 
 # abstract method 
    def noofsides(self): 
        pass
class Triangle(Polygon): 
 # overriding abstract method 
    def noofsides(self): 
        print("I have 3 sides") 
class Pentagon(Polygon): 
 # overriding abstract method 
    def noofsides(self): 
        print("I have 5 sides") 
class Hexagon(Polygon): 
 # overriding abstract method 
    def noofsides(self): 
        print("I have 6 sides") 
class Quadrilateral(Polygon): 
 # overriding abstract method 
    def noofsides(self): 
        print("I have 4 sides") 
# Driver code 
R = Triangle() 
R.noofsides() 
K = Quadrilateral() 
K.noofsides() 
R = Pentagon() 
R.noofsides() 
K = Hexagon() 
K.noofsides() 

I have 3 sides
I have 4 sides
I have 5 sides
I have 6 sides


In [ ]:
class pw_solution: # To Study
    def pow(self, x, n):
        if x==0 or x==1 or n==1:
            return x
        if x==-1:
            if n%2 ==0:
                return 1
            else:
                return -1
        if n==0:
            return 1
        if n<0:
            return 1/self.pow(x,-n)
        val = self.pow(x,n//2)
        if n%2 ==0:
            return val*val
        return val*val*x
print(pw_solution().pow(2, -3));
print(pw_solution().pow(3, 5));
print(pw_solution().pow(100, 0.25));# Not Correct Answer

0.125
243
100


In [ ]:
import numpy as np
x = np.array([1., 2., 0.4, .3])
print("Original array: ")
print(x)
r1 = np.reciprocal(x)
r2 = 1/x
assert np.array_equal(r1, r2)
print("Reciprocal for all elements of the said array:")
print(r1)
r2

Original array: 
[1.  2.  0.4 0.3]
Reciprocal for all elements of the said array:
[1.         0.5        2.5        3.33333333]


array([1.        , 0.5       , 2.5       , 3.33333333])

In [ ]:
import array as ar
ar1 = ar.array(map(int, input().split(' ')))


1 2 3 4


TypeError: array() argument 1 must be a unicode character, not map

In [ ]:
x = np.random.randint(0, 10, 40)
print("Original array:")
print(x)
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())

Original array:
[6 8 6 6 4 6 1 1 8 5 4 1 3 9 4 5 5 8 4 7 7 9 4 0 1 1 1 1 0 0 6 1 3 6 6 9 9
 6 3 8]
Most frequent value in the above array:
1


In [ ]:
x.argmax()

13

In [ ]:
np.bincount(x)

array([3, 8, 0, 3, 5, 3, 8, 2, 4, 4], dtype=int64)

In [ ]:
import numpy as np
m=int(input("Enter no. of rows: "))
n=int(input("Enter no. of columns: "))
z= np.random.randn(m,n)
x,y = z[:,0], z[:,1]
r = np.sqrt(x**2+y**2)
t = np.arctan2(y,x)
print("Cartesian Product: \n",r)
print("Polar Product: \n",t)
x

Enter no. of rows: 4
Enter no. of columns: 3
Cartesian Product: 
 [1.36025579 1.26657744 0.71500403 0.65697382]
Polar Product: 
 [-0.47262036 -0.16427315  2.66311051 -1.26051121]


array([ 1.21114252,  1.24952612, -0.63470537,  0.20059391])

In [ ]:
z

array([[ 1.21114252, -0.61921694,  0.73689969],
       [ 1.24952612, -0.20713013, -0.12506894],
       [-0.63470537,  0.32921096,  0.40477973],
       [ 0.20059391, -0.62560105,  0.05062939]])

In [ ]:
import numpy as np
m=int(input("Enter no. of rows: "))
n=int(input("Enter no. of columns: "))
z= np.random.random((m,n))
x,y = z[:,0], z[:,1]
r = np.sqrt(x**2+y**2)
t = np.arctan2(y,x)
print("Cartesian Product: \n",r)
print("Polar Product: \n",t)
x

Enter no. of rows: 3
Enter no. of columns: 4
Cartesian Product: 
 [0.906234   1.17763842 0.48790223]
Polar Product: 
 [0.17132349 0.96763364 1.07744087]


array([0.89296673, 0.6680153 , 0.23106262])

In [ ]:
z

array([[0.89296673, 0.15450076, 0.42381478, 0.35145312],
       [0.6680153 , 0.96983906, 0.33962946, 0.96188998],
       [0.23106262, 0.42971927, 0.33204039, 0.29739454]])

In [ ]:
r

array([0.906234  , 1.17763842, 0.48790223])

In [ ]:
a= np.random.randn(1,2,3,4)
a

array([[[[ 0.82153883,  1.52156753,  0.04127862,  0.15400495],
         [-1.16971238,  1.56482152, -0.52054366, -0.65725765],
         [-0.50741244,  0.50478208, -1.04387327, -0.06238672]],

        [[-1.09252575, -1.01526455, -1.26895982,  1.00726488],
         [ 0.119775  , -0.88998711,  1.14159376, -0.65334967],
         [-0.81545191, -1.87675884,  1.39371991,  1.07197357]]]])

In [ ]:
# 14. Write a Python program to find point by point distances of a random vector with shape (J,K) representing coordinates.
# import numpy as np
# x = np.random.random((3,3,3))
# print(x)
import numpy as np
j=int(input("Enter J: "))
k=int(input("Enter K: "))
a= np.random.random((j,k))
x,y = np.atleast_2d(a[:,0], a[:,1])
d = np.sqrt( (x-x.T)**2 + (y-y.T)**2)
print(d)

Enter J: 1
Enter K: 3
[[0.]]


In [ ]:
(x-x.T)**2

array([[0.]])

In [ ]:
y

array([[0.55935915]])

In [ ]:
a

array([[0.69320393, 0.55935915, 0.55607585]])

In [ ]:
import json# to study
import csv
employee_data = '{"employee_details":[{"employee_name": "James", "email": "james@gmail.com"}]}'
employee_parsed = json.loads(employee_data)
emp_data = employee_parsed['employee_details']
# open a file for writing
employ_data = open('EmployeeData.csv', 'w')
# create the csv writer object
csvwriter = csv.writer(employ_data)
count = 0
for emp in emp_data:
    if count == 0:
        header = emp.keys()
        csvwriter.writerow(header)
        count += 1
        csvwriter.writerow(emp.values())
employ_data.close()
print("DONE")

In [ ]:
import json# to study
import csv
employee_data = '{"employee_details":[{"employee_name": ["James","GD"], "email": ["james@gmail.com","a.g.damodaran@gmail.com"]}]}'
employee_parsed = json.loads(employee_data)
emp_data = employee_parsed['employee_details']
# open a file for writing
employ_data = open('EmployeeData.csv', 'w')
# create the csv writer object
csvwriter = csv.writer(employ_data)
count = 0
for emp in emp_data:
    if count == 0:
        header = emp.keys()
        csvwriter.writerow(header)
        count += 1
        csvwriter.writerow(emp.values())
employ_data.close()
print("DONE")

DONE


In [ ]:
s = pd.Series(data = [1,2,3,4,5], index = ['A', 'B', 'C','D','E'])
print("Original Data Series:")
print(s)
print()
s = s.reindex(index = ['B','A','C','D','E'])
print("Data Series after changing the order of index:")
print(s)

Original Data Series:
A    1
B    2
C    3
D    4
E    5
dtype: int64

Data Series after changing the order of index:
B    2
A    1
C    3
D    4
E    5
dtype: int64


In [ ]:
s1 = pd.Series(['100', '200', 'python', '300.12', '400'])
print("Original Data Series:")
print(s1)
print()
print("Series to an array")
a = np.array(s1.values.tolist())
print (a)

Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object

Series to an array
['100' '200' 'python' '300.12' '400']


In [ ]:
s = pd.Series([
 ['Red', 'Green', 'White'],
 ['Red', 'Black'],
 ['Yellow']])
print("Original Series of list: ")
print(s)
print()
s = s.apply(pd.Series).stack().reset_index(drop=True)
print("One Series: ")
print(s)

Original Series of list: 
0    [Red, Green, White]
1           [Red, Black]
2               [Yellow]
dtype: object

One Series: 
0       Red
1     Green
2     White
3       Red
4     Black
5    Yellow
dtype: object


In [ ]:
import pandas as pd
s = pd.Series(['100', '200', 'python', '300.12', '400'])
print("Original Data Series:")
print(s)
print()
new_s = pd.Series(s).sort_values()
print("Sorted series: ")
print(new_s)

Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object

Sorted series: 
0       100
1       200
3    300.12
4       400
2    python
dtype: object


In [ ]:
import pandas as pd
import numpy as np
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matt','GD','KA','KTA'],'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19], 'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1], 'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(exam_data , index=labels)
print("Orginal rows:")
print(df)
print()
df=df.sort_values(by=['name'], ascending=[False])
print("Sort the data frame first by ‘name’ in descending order, then by ‘score’ in ascending")
print(df)
print()
df.sort_values(by=['score'], ascending=[True])

Orginal rows:
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g       Matt   14.5         1     yes
h         GD    NaN         1      no
i         KA    8.0         2      no
j        KTA   19.0         1     yes

Sort the data frame first by ‘name’ in descending order, then by ‘score’ in ascending
        name  score  attempts qualify
f    Michael   20.0         3     yes
g       Matt   14.5         1     yes
c  Katherine   16.5         2     yes
j        KTA   19.0         1     yes
i         KA    8.0         2      no
d      James    NaN         3      no
h         GD    NaN         1      no
e      Emily    9.0         2      no
b       Dima    9.0         3      no
a  Anastasia   12.5         1     yes



name  score  attempts qualify
i         KA    8.0         2      no
e      Emily    9.0         2      no
b       Dima    9.0         3      no
a  Anastasia   12.5         1     yes
g       Matt   14.5         1     yes
c  Katherine   16.5         2     yes
j        KTA   19.0         1     yes
f    Michael   20.0         3     yes
d      James    NaN         3      no
h         GD    NaN         1      no

In [ ]:
#2. Write a Python program to get the floor, ceiling and truncated values of the elements of an numpy array.

import numpy as np
 
# input two matrices 
mat1 = ([1, 6, 5],[3 ,4, 8],[2, 12, 3]) 
mat2 = ([3, 4, 6],[5, 6, 7],[6,56, 7]) 
# This will return dot product 
res = np.dot(mat1,mat2) 
print(res) 
print(np.array(mat1))

[[ 63 320  83]
 [ 77 484 102]
 [ 84 248 117]]
[[ 1  6  5]
 [ 3  4  8]
 [ 2 12  3]]


In [ ]:
import pandas as pd
import numpy as np
#Create a DataFrame
df1 = {'Name':['George','Andrea','micheal','maggie','Ravi','Xien','Jalpa'],'University_Rank':[6,47,21,74,32,77,8]}
df1 = pd.DataFrame(df1,columns=['Nme','University_Rank'])
print(df1)
print()
df1['log_value'] = np.log(df1['University_Rank'])
df1['log2_value'] = np.log2(df1['University_Rank'])
df1['log10_value'] = np.log10(df1['University_Rank'])
print(df1)

   Nme  University_Rank
0  NaN                6
1  NaN               47
2  NaN               21
3  NaN               74
4  NaN               32
5  NaN               77
6  NaN                8

   Nme  University_Rank  log_value  log2_value  log10_value
0  NaN                6   1.791759    2.584963     0.778151
1  NaN               47   3.850148    5.554589     1.672098
2  NaN               21   3.044522    4.392317     1.322219
3  NaN               74   4.304065    6.209453     1.869232
4  NaN               32   3.465736    5.000000     1.505150
5  NaN               77   4.343805    6.266787     1.886491
6  NaN                8   2.079442    3.000000     0.903090


In [ ]:
#Develop a code to find the difference between two Timestamps in Seconds, Minutes, hours and nanoseconds in Pandas Python.
import pandas as pd
import numpy as np
import datetime
dat=input("Enter date in YYYY-MM-DD HH:MM:SS format: ")
prd=int(input("Period of years: "))
date1 = pd.Series(pd.date_range(dat, periods=prd, freq='Y'))
df = pd.DataFrame(dict(date_given=date1))
print(df)
df['Is_leap_year'] = df['date_given'].dt.is_leap_year
print(df)

Enter date in YYYY-MM-DD HH:MM:SS format: 2000-12-11 09:00:00
Period of years: 4
           date_given
0 2000-12-31 09:00:00
1 2001-12-31 09:00:00
2 2002-12-31 09:00:00
3 2003-12-31 09:00:00
           date_given  Is_leap_year
0 2000-12-31 09:00:00          True
1 2001-12-31 09:00:00         False
2 2002-12-31 09:00:00         False
3 2003-12-31 09:00:00         False


In [ ]:
#39. Write a Python program to change one value to Start_date End_date.
import pandas as pd
from dateutil.relativedelta import relativedelta
from datetime import date
date1 = pd.Series(pd.date_range('2012-1-1 00:00:00', periods=7, freq='M'))
date2 = pd.Series(pd.date_range('2013-1-1 00:00:00', periods=7, freq='W'))
df = pd.DataFrame(dict(Start_date = date1, End_date = date2))
print(df)
print()
#Difference in seconds
df['diff_seconds'] = df['End_date'] - df['Start_date']
df['diff_seconds']=df['diff_seconds']/np.timedelta64(1,'s')
#Difference in minutes
df['diff_minutes'] = df['End_date'] - df['Start_date']
df['diff_minutes']=df['diff_minutes']/np.timedelta64(1,'m')
#Difference in Hours
df['diff_hours'] = df['End_date'] - df['Start_date']
df['diff_hours']=df['diff_hours']/np.timedelta64(1,'h')
#Difference in Nanoseconds
df['diff_nano_seconds'] = df['End_date'] - df['Start_date']
df['diff_nano_seconds']=df['diff_nano_seconds']/np.timedelta64(1,'ns')
print(df)

  Start_date   End_date
0 2012-01-31 2013-01-06
1 2012-02-29 2013-01-13
2 2012-03-31 2013-01-20
3 2012-04-30 2013-01-27
4 2012-05-31 2013-02-03
5 2012-06-30 2013-02-10
6 2012-07-31 2013-02-17

  Start_date   End_date  diff_seconds  diff_minutes  diff_hours  \
0 2012-01-31 2013-01-06    29462400.0      491040.0      8184.0   
1 2012-02-29 2013-01-13    27561600.0      459360.0      7656.0   
2 2012-03-31 2013-01-20    25488000.0      424800.0      7080.0   
3 2012-04-30 2013-01-27    23500800.0      391680.0      6528.0   
4 2012-05-31 2013-02-03    21427200.0      357120.0      5952.0   
5 2012-06-30 2013-02-10    19440000.0      324000.0      5400.0   
6 2012-07-31 2013-02-17    17366400.0      289440.0      4824.0   

   diff_nano_seconds  
0       2.946240e+16  
1       2.756160e+16  
2       2.548800e+16  
3       2.350080e+16  
4       2.142720e+16  
5       1.944000e+16  
6       1.736640e+16  


In [ ]:
#10. Write a Python program to find the most frequent value in an array.

import numpy as np
n=int(input("Enter value of N: "))
x = np.random.random(n)
#x = np.random.randint(n)
print("Original array:")
print(x)
x[x.argmax()] = n
print("Maximum value replaced by -1:")
print(x)

Enter value of N: 5
Original array:
[0.88096612 0.02183088 0.44158627 0.12767355 0.43618567]
Maximum value replaced by -1:
[5.         0.02183088 0.44158627 0.12767355 0.43618567]


In [ ]:
#40. Write a NumPy program to remove the leading and trailing whitespaces of all the elements of a given array.
import pandas as pd
import numpy as np
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matt','Abbot','Juli','Pott'],'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(exam_data, index=labels)
print("Orginal rows:")
print(df)
print()

nm1=input("Enter Name to be replaced: ")
nm2=input("Enter new name: ")
print("\nChange the name %s to %s: ",nm1,nm2)
df['name'] = df['name'].replace(nm1, nm2)
print(df)

Orginal rows:
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g       Matt   14.5         1     yes
h      Abbot    NaN         1      no
i       Juli    8.0         2      no
j       Pott   19.0         1     yes

Enter Name to be replaced: Dima
Enter new name: GD

Change the name %s to %s:  Dima GD
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b         GD    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g       Matt   14.5         1     yes
h      Abbot    NaN         1      no
i       Juli    8.0         2      no
j       Pott   19.0         1     yes


In [ ]:
import numpy as np
x = np.array([' python exercises ', ' PHP ', ' java ', ' C++'], dtype=np.str)
print("Original Array:")
print(x)
stripped = np.char.strip(x)
print("\nRemove the leading and trailing whitespaces: ", stripped)

Original Array:
[' python exercises ' ' PHP ' ' java ' ' C++']

Remove the leading and trailing whitespaces:  ['python exercises' 'PHP' 'java' 'C++']


In [ ]:
a = 4
b = str(a)
b

'4'

In [ ]:
type(stripped)

numpy.ndarray

In [ ]:
stripped.shape

(4,)

In [ ]:
a = np.arange(0,8,2)
a

array([0, 2, 4, 6])

In [ ]:
n1=np.random.random(20)
n1

array([0.90421349, 0.3854544 , 0.90132975, 0.46890979, 0.3867674 ,
       0.75841576, 0.21898727, 0.86371484, 0.33001548, 0.75486222,
       0.39043744, 0.14119074, 0.62799333, 0.77716478, 0.87947967,
       0.77234383, 0.79022587, 0.96853037, 0.11375941, 0.52921719])

In [ ]:
n1=np.random.randn(1,2,3,4)
n1

array([[[[ 1.61531184,  1.47032441,  0.57304756, -0.66420481],
         [-0.06019494, -0.61394633,  0.84584443,  2.39828953],
         [-0.49889564,  0.73253751,  0.79431073, -0.06204984]],

        [[-0.78711717,  0.17217901, -0.46377176, -0.19171039],
         [-0.89909889, -0.41428183, -0.78071005,  0.2145267 ],
         [-0.03172216,  0.44709353, -0.65496534, -0.70459349]]]])

In [ ]:
n1=np.random.randint(4,13,10)
n1

array([ 6,  6,  7, 10, 11,  8,  9,  9,  4, 11])

In [ ]:
n1=np.random.normal(1,.5,500)
n1

array([ 0.93152567,  1.27838176,  0.99061462,  1.38393822,  1.26263539,
        1.44088541,  1.7309171 ,  1.73347863,  1.3621369 ,  1.34715084,
        0.66846853,  0.62203511,  0.4710556 ,  0.51593933,  0.33268306,
        0.58844706,  0.82374532,  0.7672263 ,  0.19448516,  1.48160428,
        0.95881049,  0.66593475,  1.02981518,  0.82651378,  1.73381773,
        0.83747325,  2.38078984,  0.56725038,  0.33167173,  0.69369178,
        0.77573133,  0.8363063 ,  1.41008443,  1.82459412,  0.81725686,
        1.42898065,  1.00883049,  1.24416311,  1.10408085,  0.46705119,
        0.68448875,  1.56546175,  0.62421301,  1.64134348,  1.12233619,
        1.52887141,  0.48530901,  1.01579242,  0.65892984,  0.06857899,
        1.19822139,  1.81872723,  1.50991173,  0.59230583,  0.6575285 ,
        0.31836774,  1.53409109,  1.86208241,  0.73496879,  0.4843061 ,
        0.29051311,  0.75229865,  1.51773599,  1.06478572,  0.80245941,
        0.85439752,  0.51047546,  0.95709893, -0.03578346,  0.38

In [ ]:
n1.mean()

0.9885553292668917

In [ ]:
n1.std()

0.4972031272300817

In [ ]:
np.random.choice(5,3,p=[0.1,0.2,0.3,0.4,0])

array([3, 2, 3])

In [ ]:
np.random.choice(5,3)

array([0, 1, 1])