In [ ]:
# 1. Using escape sequence print each word in different lines. Sample:
my_text='Hey! Welcome to edureka!'
for i in my_text.split(' '):
    print(i)


Hey!
Welcome
to
edureka!


In [ ]:
# 2. Write a program to create a list of even numbers starting from x to y.
x,y=input().split(' ')
x = int(x)
y = int(y)
if x%2 == 0:
    x = x
else:
    x = x+1
even_num=list(range(int(x),int(y),2))
print(even_num)

1 40
[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38]


In [ ]:
#3. Write a program to replace the given word X with Y from a string.
string=input()
X=input()
Y=input()
print(string.replace(X,Y))

true or false
true
false
false or false


In [ ]:
# 4. Write a program generate N numbers of fibbonacci series seperated by space.
N=int(input())-1
x=0
y=1
print(x,end=' ')
while N:
    c=x+y
    y=x
    x=c
    print(x,end=' ')
    N=N-1

23
0 1 1 2 3 5 8 13 21 34 55 89 144 233 377 610 987 1597 2584 4181 6765 10946 17711 

In [ ]:
# 5. Write a program to find sum of digit from a given integer number N.
N=int(input())

s_d = 0
while N:
    d = N%10
    s_d = s_d + d 
    N = N//10
print(s_d)

87658436568347
80


In [4]:
# 6. Python code to check the strength of a password.

import random
num = random.randint(1,6)
print(num)

4


In [5]:
# 2. Write a python script to debit and credit money from a bank account using functions.

def make_account():
    return {'balance': 0}
def deposit(account, amount):
    account['balance'] += amount
    print("Deposit Balance:",account['balance'])
    return account['balance']
def withdraw(account, amount):
    account['balance'] -= amount
    print("Withdrawl Balance: ",account['balance'])
    return account['balance']

a=make_account()

In [6]:
a

{'balance': 0}

In [8]:
choice = int(input('Deposit - 1 or Withdraw - 2: '))
amt = int(input("Enter amount to be deposited or withdrawn: "))
if choice == 1:
    deposit(a,amt)
else:
    withdraw(a,amt)

Deposit - 1 or Withdraw - 2: 1
Enter amount to be deposited or withdrawn: 6000
Deposit Balance: 5500


In [9]:
a

{'balance': 5500}

In [ ]:
# 6a. Write a prg to find a factors of a Number
N = int(input())

for i in range(1,N+1):
    if N%i == 0:
        print(i)

20
1
2
4
5
10
20


In [ ]:
# 6. Write a prg to find a factorial of a Number
N = int(input())
f=1
for i in range(1,N+1):
    f = f*i
print(f)

6
720


In [ ]:
# 7-9. Following Pattern
for i in range(7):
    print(' '*(7-i)+'^'*(2*(i+1)-1))

       ^
      ^^^
     ^^^^^
    ^^^^^^^
   ^^^^^^^^^
  ^^^^^^^^^^^
 ^^^^^^^^^^^^^


In [ ]:
# 10. Following Pattern
n = int(input())
cnt = 0
for i in range(n):
    for j in range(i):
        cnt = cnt + 1
        print(cnt, end=' ')
    print()

5

1 
2 3 
4 5 6 
7 8 9 10 


In [ ]:
n = int(input())
cnt = 0
for i in range(n+1):
    cnt = i
    for j in range(i):
        print(cnt, end=' ')
        cnt = cnt + 1
        
    print()

5

1 
2 3 
3 4 5 
4 5 6 7 
5 6 7 8 9 


In [ ]:
# 11. Write a prg to accept n values and print as list
n = int(input())
l =[]
for i in range(n):
    l.append(int(input()))
print(l)

5
1
2
3
4
5
[1, 2, 3, 4, 5]


In [ ]:
#12. Armstrong Yes or No
arms = input()
a = 0
for i in list(arms):
    j = int(i)
    a = a + j**3
if a == int(arms):
    print('Armstrong')
else:
    print('Not Armstrong')

153
Armstrong


In [ ]:
# 13. Nth arthmetic progression number given a and d
n = int(input())
a = int(input())
d = int(input())
dn = a + (n-1)*d
print(dn)

5
5
3
17


In [ ]:
#14. GP sequence given a and r
n,a,r = map(int,input().split(','))
# n = int(input())
# a = int(input())
# r = int(input())
l = []
for i in range(n):
    dn = a*r**i
    print(dn,end=' ')
    l.append(dn)

5,2,3
2 6 18 54 162 

In [ ]:
l

[2, 6, 18, 54, 162]

In [10]:
# 15. Prg to calc lower, upper & digit Finding digit, Upper & Lower case char in a sentence
sent = input()
l = 0
u = 0
d = 0
for i in sent:
    if i.isupper():
        u = u + 1
    elif i.islower():
        l = l + 1
    elif i.isdigit():
        d = d + 1
print('lower :', l)
print('upper :', u)
print('digit :', d)

rtt 656 ouADSGDH KJ
lower : 5
upper : 8
digit : 3


In [12]:
[i for i in 'sent']

['s', 'e', 'n', 't']

In [ ]:
# 16. Palindrome
s = input()
if s[::-1] == s:
    print('Palindrome')
else:
    print('No Palindrome')

mayam
Palindrome


In [ ]:
# 17. Append list and sorting
n = input()
l = []
for i in range(int(n)):
    l.append(int(input()))
l.sort()
l

4
3
4
21
3


[3, 3, 4, 21]

In [14]:
#18.Given below a list of integers, find the triplets whose sum if equal to zero and print them as tuples.
l = [0, 2, 3, 4, 5, 6, 9, -1, -9, -7, -6, -5, -4, -3, -2]
n = []

dset = set(l)
for i in l:
    for j in l[i+1:]:
        k = i+j
        if -k in dset and i!=j and j!=-k and -k!=i:
            tlist = [i,j,-k]
            tlist.sort()          
            n.append(tuple(tlist))
o=[]
for i in range(len(n)):
    j=n[i]
    if j not in n[i+1:]:
        print(tuple(j))
#         o.append(j)
# print(tuple(o))

(-9, 0, 9)
(-2, 0, 2)
(-5, 2, 3)
(-3, 0, 3)
(-7, 3, 4)
(-6, 2, 4)
(-4, 0, 4)
(-9, 4, 5)
(-7, 2, 5)
(-5, 0, 5)
(-9, 3, 6)
(-6, 0, 6)
(-5, -1, 6)
(-4, -1, 5)
(-3, -1, 4)
(-2, -1, 3)
(-7, -2, 9)
(-6, -3, 9)
(-5, -4, 9)
(-4, -2, 6)
(-3, -2, 5)


In [13]:
num_list = [0, 2, 3, 4, 5, 6, 9, -1, -9, -7, -6, -5, -4, -3, -2]
n = len(num_list)
for i in range(n - 1): 
    s = set()  
    for j in range(i + 1, n): 
        x = -(num_list[i] + num_list[j]) 
        if x in s:  
            print((x, num_list[i], num_list[j])) 
        else:  
            s.add(num_list[j])


(9, 0, -9)
(6, 0, -6)
(5, 0, -5)
(4, 0, -4)
(3, 0, -3)
(2, 0, -2)
(5, 2, -7)
(4, 2, -6)
(3, 2, -5)
(6, 3, -9)
(4, 3, -7)
(-1, 3, -2)
(5, 4, -9)
(-1, 4, -3)
(-1, 5, -4)
(-3, 5, -2)
(-1, 6, -5)
(-4, 6, -2)
(-5, 9, -4)
(-6, 9, -3)
(-7, 9, -2)


In [ ]:
s

{-2}

In [ ]:
# 19. Print alphabet with space
x,y = map(int, input().split(' '))
for i in range(x,y):
    print(chr(i),end=' ')

0 20000
        	 


                     ! " # $ % & ' ( ) * + , - . / 0 1 2 3 4 5 6 7 8 9 : ; < = > ? @ A B C D E F G H I J K L M N O P Q R S T U V W X Y Z [ \ ] ^ _ ` a b c d e f g h i j k l m n o p q r s t u v w x y z { | } ~  €  ‚ ƒ „ … † ‡ ˆ ‰ Š ‹ Œ  Ž   ‘ ’ “ ” • – — ˜ ™ š › œ  ž Ÿ   ¡ ¢ £ ¤ ¥ ¦ § ¨ © ª « ¬ ­ ® ¯ ° ± ² ³ ´ µ ¶ · ¸ ¹ º » ¼ ½ ¾ ¿ À Á Â Ã Ä Å Æ Ç È É Ê Ë Ì Í Î Ï Ð Ñ Ò Ó Ô Õ Ö × Ø Ù Ú Û Ü Ý Þ ß à á â ã ä å æ ç è é ê ë ì í î ï ð ñ ò ó ô õ ö ÷ ø ù ú û ü ý þ ÿ Ā ā Ă ă Ą ą Ć ć Ĉ ĉ Ċ ċ Č č Ď ď Đ đ Ē ē Ĕ ĕ Ė ė Ę ę Ě ě Ĝ ĝ Ğ ğ Ġ ġ Ģ ģ Ĥ ĥ Ħ ħ Ĩ ĩ Ī ī Ĭ ĭ Į į İ ı IJ ij Ĵ ĵ Ķ ķ ĸ Ĺ ĺ Ļ ļ Ľ ľ Ŀ ŀ Ł ł Ń ń Ņ ņ Ň ň ʼn Ŋ ŋ Ō ō Ŏ ŏ Ő ő Œ œ Ŕ ŕ Ŗ ŗ Ř ř Ś ś Ŝ ŝ Ş ş Š š Ţ ţ Ť ť Ŧ ŧ Ũ ũ Ū ū Ŭ ŭ Ů ů Ű ű Ų ų Ŵ ŵ Ŷ ŷ Ÿ Ź ź Ż ż Ž ž ſ ƀ Ɓ Ƃ ƃ Ƅ ƅ Ɔ Ƈ ƈ Ɖ Ɗ Ƌ ƌ ƍ Ǝ Ə Ɛ Ƒ ƒ Ɠ Ɣ ƕ Ɩ Ɨ Ƙ ƙ ƚ ƛ Ɯ Ɲ ƞ Ɵ Ơ ơ Ƣ ƣ Ƥ ƥ Ʀ Ƨ ƨ Ʃ ƪ ƫ Ƭ ƭ Ʈ Ư ư Ʊ Ʋ Ƴ ƴ Ƶ ƶ Ʒ Ƹ ƹ ƺ ƻ Ƽ ƽ ƾ ƿ ǀ ǁ ǂ ǃ DŽ Dž dž LJ Lj lj NJ Nj nj Ǎ ǎ Ǐ ǐ Ǒ ǒ Ǔ ǔ Ǖ ǖ Ǘ ǘ Ǚ ǚ Ǜ ǜ ǝ Ǟ ǟ Ǡ ǡ Ǣ ǣ Ǥ ǥ Ǧ ǧ Ǩ ǩ Ǫ ǫ Ǭ ǭ Ǯ ǯ ǰ DZ Dz dz Ǵ ǵ Ƕ Ƿ Ǹ ǹ Ǻ ǻ Ǽ ǽ Ǿ ǿ Ȁ ȁ

ᜎ ᜏ ᜐ ᜑ ᜒ ᜓ ᜔ ᜕ ᜖ ᜗ ᜘ ᜙ ᜚ ᜛ ᜜ ᜝ ᜞ ᜟ ᜠ ᜡ ᜢ ᜣ ᜤ ᜥ ᜦ ᜧ ᜨ ᜩ ᜪ ᜫ ᜬ ᜭ ᜮ ᜯ ᜰ ᜱ ᜲ ᜳ ᜴ ᜵ ᜶ ᜷ ᜸ ᜹ ᜺ ᜻ ᜼ ᜽ ᜾ ᜿ ᝀ ᝁ ᝂ ᝃ ᝄ ᝅ ᝆ ᝇ ᝈ ᝉ ᝊ ᝋ ᝌ ᝍ ᝎ ᝏ ᝐ ᝑ ᝒ ᝓ ᝔ ᝕ ᝖ ᝗ ᝘ ᝙ ᝚ ᝛ ᝜ ᝝ ᝞ ᝟ ᝠ ᝡ ᝢ ᝣ ᝤ ᝥ ᝦ ᝧ ᝨ ᝩ ᝪ ᝫ ᝬ ᝭ ᝮ ᝯ ᝰ ᝱ ᝲ ᝳ ᝴ ᝵ ᝶ ᝷ ᝸ ᝹ ᝺ ᝻ ᝼ ᝽ ᝾ ᝿ ក ខ គ ឃ ង ច ឆ ជ ឈ ញ ដ ឋ ឌ ឍ ណ ត ថ ទ ធ ន ប ផ ព ភ ម យ រ ល វ ឝ ឞ ស ហ ឡ អ ឣ ឤ ឥ ឦ ឧ ឨ ឩ ឪ ឫ ឬ ឭ ឮ ឯ ឰ ឱ ឲ ឳ ឴ ឵ ា ិ ី ឹ ឺ ុ ូ ួ ើ ឿ ៀ េ ែ ៃ ោ ៅ ំ ះ ៈ ៉ ៊ ់ ៌ ៍ ៎ ៏ ័ ៑ ្ ៓ ។ ៕ ៖ ៗ ៘ ៙ ៚ ៛ ៜ ៝ ៞ ៟ ០ ១ ២ ៣ ៤ ៥ ៦ ៧ ៨ ៩ ៪ ៫ ៬ ៭ ៮ ៯ ៰ ៱ ៲ ៳ ៴ ៵ ៶ ៷ ៸ ៹ ៺ ៻ ៼ ៽ ៾ ៿ ᠀ ᠁ ᠂ ᠃ ᠄ ᠅ ᠆ ᠇ ᠈ ᠉ ᠊ ᠋ ᠌ ᠍ ᠎ ᠏ ᠐ ᠑ ᠒ ᠓ ᠔ ᠕ ᠖ ᠗ ᠘ ᠙ ᠚ ᠛ ᠜ ᠝ ᠞ ᠟ ᠠ ᠡ ᠢ ᠣ ᠤ ᠥ ᠦ ᠧ ᠨ ᠩ ᠪ ᠫ ᠬ ᠭ ᠮ ᠯ ᠰ ᠱ ᠲ ᠳ ᠴ ᠵ ᠶ ᠷ ᠸ ᠹ ᠺ ᠻ ᠼ ᠽ ᠾ ᠿ ᡀ ᡁ ᡂ ᡃ ᡄ ᡅ ᡆ ᡇ ᡈ ᡉ ᡊ ᡋ ᡌ ᡍ ᡎ ᡏ ᡐ ᡑ ᡒ ᡓ ᡔ ᡕ ᡖ ᡗ ᡘ ᡙ ᡚ ᡛ ᡜ ᡝ ᡞ ᡟ ᡠ ᡡ ᡢ ᡣ ᡤ ᡥ ᡦ ᡧ ᡨ ᡩ ᡪ ᡫ ᡬ ᡭ ᡮ ᡯ ᡰ ᡱ ᡲ ᡳ ᡴ ᡵ ᡶ ᡷ ᡸ ᡹ ᡺ ᡻ ᡼ ᡽ ᡾ ᡿ ᢀ ᢁ ᢂ ᢃ ᢄ ᢅ ᢆ ᢇ ᢈ ᢉ ᢊ ᢋ ᢌ ᢍ ᢎ ᢏ ᢐ ᢑ ᢒ ᢓ ᢔ ᢕ ᢖ ᢗ ᢘ ᢙ ᢚ ᢛ ᢜ ᢝ ᢞ ᢟ ᢠ ᢡ ᢢ ᢣ ᢤ ᢥ ᢦ ᢧ ᢨ ᢩ ᢪ ᢫ ᢬ ᢭ ᢮ ᢯ ᢰ ᢱ ᢲ ᢳ ᢴ ᢵ ᢶ ᢷ ᢸ ᢹ ᢺ ᢻ ᢼ ᢽ ᢾ ᢿ ᣀ ᣁ ᣂ ᣃ ᣄ ᣅ ᣆ ᣇ ᣈ ᣉ ᣊ ᣋ ᣌ ᣍ ᣎ ᣏ ᣐ ᣑ ᣒ ᣓ ᣔ ᣕ ᣖ ᣗ ᣘ ᣙ ᣚ ᣛ ᣜ ᣝ ᣞ ᣟ ᣠ ᣡ ᣢ ᣣ ᣤ ᣥ ᣦ ᣧ ᣨ ᣩ ᣪ ᣫ ᣬ ᣭ ᣮ ᣯ ᣰ ᣱ ᣲ ᣳ ᣴ ᣵ ᣶ ᣷ ᣸ ᣹ ᣺ ᣻ ᣼ ᣽ ᣾ ᣿ ᤀ ᤁ 

 ⭚ ⭛ ⭜ ⭝ ⭞ ⭟ ⭠ ⭡ ⭢ ⭣ ⭤ ⭥ ⭦ ⭧ ⭨ ⭩ ⭪ ⭫ ⭬ ⭭ ⭮ ⭯ ⭰ ⭱ ⭲ ⭳ ⭴ ⭵ ⭶ ⭷ ⭸ ⭹ ⭺ ⭻ ⭼ ⭽ ⭾ ⭿ ⮀ ⮁ ⮂ ⮃ ⮄ ⮅ ⮆ ⮇ ⮈ ⮉ ⮊ ⮋ ⮌ ⮍ ⮎ ⮏ ⮐ ⮑ ⮒ ⮓ ⮔ ⮕ ⮖ ⮗ ⮘ ⮙ ⮚ ⮛ ⮜ ⮝ ⮞ ⮟ ⮠ ⮡ ⮢ ⮣ ⮤ ⮥ ⮦ ⮧ ⮨ ⮩ ⮪ ⮫ ⮬ ⮭ ⮮ ⮯ ⮰ ⮱ ⮲ ⮳ ⮴ ⮵ ⮶ ⮷ ⮸ ⮹ ⮺ ⮻ ⮼ ⮽ ⮾ ⮿ ⯀ ⯁ ⯂ ⯃ ⯄ ⯅ ⯆ ⯇ ⯈ ⯉ ⯊ ⯋ ⯌ ⯍ ⯎ ⯏ ⯐ ⯑ ⯒ ⯓ ⯔ ⯕ ⯖ ⯗ ⯘ ⯙ ⯚ ⯛ ⯜ ⯝ ⯞ ⯟ ⯠ ⯡ ⯢ ⯣ ⯤ ⯥ ⯦ ⯧ ⯨ ⯩ ⯪ ⯫ ⯬ ⯭ ⯮ ⯯ ⯰ ⯱ ⯲ ⯳ ⯴ ⯵ ⯶ ⯷ ⯸ ⯹ ⯺ ⯻ ⯼ ⯽ ⯾ ⯿ Ⰰ Ⰱ Ⰲ Ⰳ Ⰴ Ⰵ Ⰶ Ⰷ Ⰸ Ⰹ Ⰺ Ⰻ Ⰼ Ⰽ Ⰾ Ⰿ Ⱀ Ⱁ Ⱂ Ⱃ Ⱄ Ⱅ Ⱆ Ⱇ Ⱈ Ⱉ Ⱊ Ⱋ Ⱌ Ⱍ Ⱎ Ⱏ Ⱐ Ⱑ Ⱒ Ⱓ Ⱔ Ⱕ Ⱖ Ⱗ Ⱘ Ⱙ Ⱚ Ⱛ Ⱜ Ⱝ Ⱞ Ⱟ ⰰ ⰱ ⰲ ⰳ ⰴ ⰵ ⰶ ⰷ ⰸ ⰹ ⰺ ⰻ ⰼ ⰽ ⰾ ⰿ ⱀ ⱁ ⱂ ⱃ ⱄ ⱅ ⱆ ⱇ ⱈ ⱉ ⱊ ⱋ ⱌ ⱍ ⱎ ⱏ ⱐ ⱑ ⱒ ⱓ ⱔ ⱕ ⱖ ⱗ ⱘ ⱙ ⱚ ⱛ ⱜ ⱝ ⱞ ⱟ Ⱡ ⱡ Ɫ Ᵽ Ɽ ⱥ ⱦ Ⱨ ⱨ Ⱪ ⱪ Ⱬ ⱬ Ɑ Ɱ Ɐ Ɒ ⱱ Ⱳ ⱳ ⱴ Ⱶ ⱶ ⱷ ⱸ ⱹ ⱺ ⱻ ⱼ ⱽ Ȿ Ɀ Ⲁ ⲁ Ⲃ ⲃ Ⲅ ⲅ Ⲇ ⲇ Ⲉ ⲉ Ⲋ ⲋ Ⲍ ⲍ Ⲏ ⲏ Ⲑ ⲑ Ⲓ ⲓ Ⲕ ⲕ Ⲗ ⲗ Ⲙ ⲙ Ⲛ ⲛ Ⲝ ⲝ Ⲟ ⲟ Ⲡ ⲡ Ⲣ ⲣ Ⲥ ⲥ Ⲧ ⲧ Ⲩ ⲩ Ⲫ ⲫ Ⲭ ⲭ Ⲯ ⲯ Ⲱ ⲱ Ⲳ ⲳ Ⲵ ⲵ Ⲷ ⲷ Ⲹ ⲹ Ⲻ ⲻ Ⲽ ⲽ Ⲿ ⲿ Ⳁ ⳁ Ⳃ ⳃ Ⳅ ⳅ Ⳇ ⳇ Ⳉ ⳉ Ⳋ ⳋ Ⳍ ⳍ Ⳏ ⳏ Ⳑ ⳑ Ⳓ ⳓ Ⳕ ⳕ Ⳗ ⳗ Ⳙ ⳙ Ⳛ ⳛ Ⳝ ⳝ Ⳟ ⳟ Ⳡ ⳡ Ⳣ ⳣ ⳤ ⳥ ⳦ ⳧ ⳨ ⳩ ⳪ Ⳬ ⳬ Ⳮ ⳮ ⳯ ⳰ ⳱ Ⳳ ⳳ ⳴ ⳵ ⳶ ⳷ ⳸ ⳹ ⳺ ⳻ ⳼ ⳽ ⳾ ⳿ ⴀ ⴁ ⴂ ⴃ ⴄ ⴅ ⴆ ⴇ ⴈ ⴉ ⴊ ⴋ ⴌ ⴍ ⴎ ⴏ ⴐ ⴑ ⴒ ⴓ ⴔ ⴕ ⴖ ⴗ ⴘ ⴙ ⴚ ⴛ ⴜ ⴝ ⴞ ⴟ ⴠ ⴡ ⴢ ⴣ ⴤ ⴥ ⴦ ⴧ ⴨ ⴩ ⴪ ⴫ ⴬ ⴭ ⴮ ⴯ ⴰ ⴱ ⴲ ⴳ ⴴ ⴵ ⴶ ⴷ ⴸ ⴹ ⴺ ⴻ ⴼ ⴽ ⴾ ⴿ ⵀ ⵁ ⵂ ⵃ ⵄ ⵅ ⵆ ⵇ ⵈ ⵉ ⵊ ⵋ ⵌ ⵍ

䀦 䀧 䀨 䀩 䀪 䀫 䀬 䀭 䀮 䀯 䀰 䀱 䀲 䀳 䀴 䀵 䀶 䀷 䀸 䀹 䀺 䀻 䀼 䀽 䀾 䀿 䁀 䁁 䁂 䁃 䁄 䁅 䁆 䁇 䁈 䁉 䁊 䁋 䁌 䁍 䁎 䁏 䁐 䁑 䁒 䁓 䁔 䁕 䁖 䁗 䁘 䁙 䁚 䁛 䁜 䁝 䁞 䁟 䁠 䁡 䁢 䁣 䁤 䁥 䁦 䁧 䁨 䁩 䁪 䁫 䁬 䁭 䁮 䁯 䁰 䁱 䁲 䁳 䁴 䁵 䁶 䁷 䁸 䁹 䁺 䁻 䁼 䁽 䁾 䁿 䂀 䂁 䂂 䂃 䂄 䂅 䂆 䂇 䂈 䂉 䂊 䂋 䂌 䂍 䂎 䂏 䂐 䂑 䂒 䂓 䂔 䂕 䂖 䂗 䂘 䂙 䂚 䂛 䂜 䂝 䂞 䂟 䂠 䂡 䂢 䂣 䂤 䂥 䂦 䂧 䂨 䂩 䂪 䂫 䂬 䂭 䂮 䂯 䂰 䂱 䂲 䂳 䂴 䂵 䂶 䂷 䂸 䂹 䂺 䂻 䂼 䂽 䂾 䂿 䃀 䃁 䃂 䃃 䃄 䃅 䃆 䃇 䃈 䃉 䃊 䃋 䃌 䃍 䃎 䃏 䃐 䃑 䃒 䃓 䃔 䃕 䃖 䃗 䃘 䃙 䃚 䃛 䃜 䃝 䃞 䃟 䃠 䃡 䃢 䃣 䃤 䃥 䃦 䃧 䃨 䃩 䃪 䃫 䃬 䃭 䃮 䃯 䃰 䃱 䃲 䃳 䃴 䃵 䃶 䃷 䃸 䃹 䃺 䃻 䃼 䃽 䃾 䃿 䄀 䄁 䄂 䄃 䄄 䄅 䄆 䄇 䄈 䄉 䄊 䄋 䄌 䄍 䄎 䄏 䄐 䄑 䄒 䄓 䄔 䄕 䄖 䄗 䄘 䄙 䄚 䄛 䄜 䄝 䄞 䄟 䄠 䄡 䄢 䄣 䄤 䄥 䄦 䄧 䄨 䄩 䄪 䄫 䄬 䄭 䄮 䄯 䄰 䄱 䄲 䄳 䄴 䄵 䄶 䄷 䄸 䄹 䄺 䄻 䄼 䄽 䄾 䄿 䅀 䅁 䅂 䅃 䅄 䅅 䅆 䅇 䅈 䅉 䅊 䅋 䅌 䅍 䅎 䅏 䅐 䅑 䅒 䅓 䅔 䅕 䅖 䅗 䅘 䅙 䅚 䅛 䅜 䅝 䅞 䅟 䅠 䅡 䅢 䅣 䅤 䅥 䅦 䅧 䅨 䅩 䅪 䅫 䅬 䅭 䅮 䅯 䅰 䅱 䅲 䅳 䅴 䅵 䅶 䅷 䅸 䅹 䅺 䅻 䅼 䅽 䅾 䅿 䆀 䆁 䆂 䆃 䆄 䆅 䆆 䆇 䆈 䆉 䆊 䆋 䆌 䆍 䆎 䆏 䆐 䆑 䆒 䆓 䆔 䆕 䆖 䆗 䆘 䆙 䆚 䆛 䆜 䆝 䆞 䆟 䆠 䆡 䆢 䆣 䆤 䆥 䆦 䆧 䆨 䆩 䆪 䆫 䆬 䆭 䆮 䆯 䆰 䆱 䆲 䆳 䆴 䆵 䆶 䆷 䆸 䆹 䆺 䆻 䆼 䆽 䆾 䆿 䇀 䇁 䇂 䇃 䇄 䇅 䇆 䇇 䇈 䇉 䇊 䇋 䇌 䇍 䇎 䇏 䇐 䇑 䇒 䇓 䇔 䇕 䇖 䇗 䇘 䇙 䇚 䇛 䇜 䇝 䇞 䇟 䇠 䇡 䇢 䇣 䇤 䇥 䇦 䇧 䇨 䇩 䇪 䇫 䇬 䇭 䇮 䇯 䇰 䇱 䇲 䇳 䇴 䇵 䇶 䇷 䇸 䇹 䇺 䇻 䇼 䇽 䇾 䇿 䈀 䈁 䈂 䈃 䈄 䈅 䈆 䈇 䈈 䈉 䈊 䈋 䈌 䈍 䈎 䈏 䈐 䈑 䈒 䈓 䈔 䈕 䈖 䈗 䈘 䈙 

In [16]:
s = input()
for i in s:
    print(ascii(i),end=' ')

yti
'y' 't' 'i' 

In [ ]:
#20. Given two sets find the intersection has edureka
# a = {'c','a','d','e','k','r','u','q','r','y','g'}
a = {'c','a','d','e','k','r','u','q','r','y'}
b = {'b','h','k','a','d','e','r','u','g'}

w = set(list('edureka'))
if len(a.intersection(b).difference(w)) == 0:
    print('Yes')
else:
    print('No')
a.intersection(b)#.difference(w)

Yes


{'a', 'd', 'e', 'k', 'r', 'u'}

In [ ]:
w

{'a', 'd', 'e', 'k', 'r', 'u'}

In [ ]:
a.intersection(b).difference(w)

set()

In [ ]:
#21. Reversing string from input
s = input()
print(s[::-1])

Damodaran is to improve
evorpmi ot si naradomaD


In [17]:
#22. Reversing words only in string from input
s = input()
l = s.split(' ')
rstr =''
for i in l:
    print(i[::-1], end=' ')
    rstr = rstr + i[::-1]+ ' '
print()
print(rstr)

My Name Is GD
yM emaN sI DG 
yM emaN sI DG 


In [ ]:
#23. No. between x and y divisible by 5 and 13 but not by 10 sep by space

x = int(input())
y = int(input())

for i in range(x,y+1):
    if i%5 == 0 and i%13 == 0 and i%10 !=0:
        print(i,end=' ')
                

50
200
65 195 

In [21]:
#24. All possible permutation for list of n numbers - Logic of inserting new element at all possible position and loop the same
n = int(input('n:'))
l = []
for j in range(n):
    l.append(input(f'x({j}) :'))
perm = [[]]
for x in l:
    temp = []
    print()
    print(perm)
    for p in perm:
        for i in range(len(p)+1):
            print()
            print(x)
            print(p)
            temp.append(p[:i] + [x] + p[i:])
            perm = temp
            print(temp)      
print()
print(perm)

n:3
x("0") :a
x("1") :b
x("2") :c

[[]]

a
[]
[['a']]

[['a']]

b
['a']
[['b', 'a']]

b
['a']
[['b', 'a'], ['a', 'b']]

[['b', 'a'], ['a', 'b']]

c
['b', 'a']
[['c', 'b', 'a']]

c
['b', 'a']
[['c', 'b', 'a'], ['b', 'c', 'a']]

c
['b', 'a']
[['c', 'b', 'a'], ['b', 'c', 'a'], ['b', 'a', 'c']]

c
['a', 'b']
[['c', 'b', 'a'], ['b', 'c', 'a'], ['b', 'a', 'c'], ['c', 'a', 'b']]

c
['a', 'b']
[['c', 'b', 'a'], ['b', 'c', 'a'], ['b', 'a', 'c'], ['c', 'a', 'b'], ['a', 'c', 'b']]

c
['a', 'b']
[['c', 'b', 'a'], ['b', 'c', 'a'], ['b', 'a', 'c'], ['c', 'a', 'b'], ['a', 'c', 'b'], ['a', 'b', 'c']]

[['c', 'b', 'a'], ['b', 'c', 'a'], ['b', 'a', 'c'], ['c', 'a', 'b'], ['a', 'c', 'b'], ['a', 'b', 'c']]


In [ ]:
#25. Performance of students using dictionary
test = {'English':{'A':80,'B':67,'C':78,'D':89},'Tamil':{'A':80,'B':87,'C':67,'D':67},
        'Maths':{'A':78,'B':90,'D':68,'E':98},'Science':{'E':78,'D':90,'A':78,'B':78}}

stu = []

for i in test:
    stu.extend(test[i].keys())
print(stu)
set_stu = set(stu)
stu = list(set_stu)
stu.sort()

T = {}

for i in range(len(stu)):
    key = stu[i]
    T[key] = 0
print(T)

T_mrks = dict.fromkeys(stu,0)
print(T_mrks)

for i in test:
    print(i)
    for j in test[i]:
        print(j)
        T[j] = T[j] + test[i][j] # ok
print(T)
Avg={}
for x in T:
    Avg[x] = T[x]/len(test)
    
Avg

['A', 'B', 'C', 'D', 'A', 'B', 'C', 'D', 'A', 'B', 'D', 'E', 'E', 'D', 'A', 'B']
{'A': 0, 'B': 0, 'C': 0, 'D': 0, 'E': 0}
{'A': 0, 'B': 0, 'C': 0, 'D': 0, 'E': 0}
English
A
B
C
D
Tamil
A
B
C
D
Maths
A
B
D
E
Science
E
D
A
B
{'A': 316, 'B': 322, 'C': 145, 'D': 314, 'E': 176}


{'A': 79.0, 'B': 80.5, 'C': 36.25, 'D': 78.5, 'E': 44.0}

In [ ]:
s

{'A', 'B', 'C', 'D', 'E'}

In [ ]:
test['English']

{'A': 80, 'B': 67, 'C': 78, 'D': 89}

In [ ]:
stu

['A', 'B', 'C', 'D', 'E']

In [ ]:
#26. Student record appending in dictionary

#Keys - Name, Class, Age

stu_data = {'Name':[],'Class':[],'Age':[]}

for i in range(5):
    stu_data['Name'].append(input('Name:'))
    stu_data['Class'].append(input('Class:'))
    stu_data['Age'].append(input('Age:'))
    
stu_data

In [ ]:
#27. dictionary concatenation

d1 = {'Name': ['Damodaran G', 'Keerthi D', 'Pranav D', 'Shilpa L', 'Yalu J']}
d2 = {'Class': ['X', 'V', 'PreKG', 'XX', 'PreKG']}
d3 = {'Age': ['16', '9', '3', '15', '3']}

d = {}

d.update(d1)
d.update(d2)
d.update(d3)

d

{'Name': ['Damodaran G', 'Keerthi D', 'Pranav D', 'Shilpa L', 'Yalu J'],
 'Class': ['X', 'V', 'PreKG', 'XX', 'PreKG'],
 'Age': ['16', '9', '3', '15', '3']}

In [ ]:
#28. prime no generation and store it in a text file

file = open('prime.txt', 'w')

n = int(input())

for i in range(2,n):
    flg = True
    for j in range(2,i):
        if i%j == 0:
            flg = False
            break
    if flg:
        #print(i)
        file.write(str(i)+'\n ')
file.close()
lno = int(input())
file = open('prime.txt','r')
file.readline(lno)
file.tell()
# file.close()

100
6


3

In [ ]:
file.readline(45)
file.tell()

7

In [ ]:
file.readlines(90)

[' 53\n',
 ' 59\n',
 ' 61\n',
 ' 67\n',
 ' 71\n',
 ' 73\n',
 ' 79\n',
 ' 83\n',
 ' 89\n',
 ' 97\n',
 ' ']

In [22]:
for alphabet in range(97,123): 
 print(chr(alphabet),end=' ')

a b c d e f g h i j k l m n o p q r s t u v w x y z 

In [23]:
import datetime
 
def numOfDays(date1, date2): 
 return (date2-date1).days
 
date1_ent = input('Enter a date in YYYY-MM-DD format: ')
year, month, day = map(int, date1_ent.split('-'))
date1 = datetime.date(year, month, day)
date2_ent = input('Enter a date in YYYY-MM-DD format: ')
year, month, day = map(int, date2_ent.split('-'))
date2 = datetime.date(year, month, day) 
print(numOfDays(date1, date2), "days")

Enter a date in YYYY-MM-DD format: 2000-03-17
Enter a date in YYYY-MM-DD format: 2020-11-28
7561 days


In [31]:
(date2-date1).days

7561

In [38]:
import re 
 
s=input("Enter text: ") 
lst = re.findall('\S+@[a-z]+.com$', s) 
print(lst) 
# Input: Enter text: john.doe@gmail.com
# Output: ['john.doe@gmail.com']

Enter text: john.doe@gmail.com john.doe@gmail.com john.doe@gmail.com
['john.doe@gmail.com', 'john.doe@gmail.com', 'john.doe@gmail.com']


In [ ]:
import string,random
n=int(input("Enter length of password: "))
passw= ''.join(random.choice(string.ascii_uppercase + string.ascii_lowercase + string.digit))
print(passw)

In [46]:
import re

def password():
  print ('Enter a password\n\nThe password must be between 6 and 12 characters.\n')
  while True:
    password = input('Password: ')
    if 6 <= len(password) < 12:
      break
      print('The password must be between 6 and 12 characters.\n')
    password_scores = {0:'Horrible', 1:'Weak', 2:'Medium', 3:'Strong'}
    password_strength = dict.fromkeys(['has_upper', 'has_lower', 'has_num'], False)
    if re.search(r'[A-Z]', password):
      password_strength['has_upper'] = True
    if re.search(r'[a-z]', password):
      password_strength['has_lower'] = True
    if re.search(r'[0-9]', password):
      password_strength['has_num'] = True
  print([b for b in password_strength.values() if b])
  score = len([b for b in password_strength.values() if b])
  print('Password is %s' % password_scores[score])
password()

Enter a password

The password must be between 6 and 12 characters.

Password: jbvsj3434343
Password: jjgjg687
[True, True]
Password is Medium


In [47]:
import math
def sqrfunc(n):
 return lambda n:n*n
def cubefunc(n):
 return lambda n:n*n*n
def sqrtfunc(n):
 return lambda n: math.sqrt(n)
n= int(input("Enter a number: "))
sqr = sqrfunc(n)
cube= cubefunc(n)
sqrrt=sqrtfunc(n)
print("Square: ",sqr(n))
print("Cube: ",cube(n))
print("Square Root: ",sqrrt(n))

Enter a number: 4
Square:  16
Cube:  64
Square Root:  2.0


In [49]:
import math

#formulas for each geometric figure
def calc_square(a_side):
 square_area = a_side ** 2
 return square_area
def calc_rectangle(w_side, l_side):
 rect_area = l_side * w_side
 return rect_area
def calc_triangle(base, height):
 triangle_area = (base * height) / 2
 return triangle_area
def calc_circle(radius):
 circle_area = math.pi * radius ** 2
 return circle_area
def calc_trapezoid(short_base, long_base, height):
 trapezoid_area = ((short_base + long_base) / 2 ) * height
 return trapezoid_area

#function determining which formula to calculate
def area_calc_logic(user_calc):
 if user_calc == "square":
  a_side = float(input("Give length of side: "))
  print("Area: ",calc_square(a_side))
 elif user_calc == "rectangle":
  l_side = float(input("Give the length: "))
  w_side = float(input("Give the width: "))
  print("Area: ",calc_rectangle(w_side, l_side))
 elif user_calc == "triangle":
  base = float(input("Give the length of base: "))
  height = float(input("Give the height: "))
  print("Area: ",calc_triangle(base, height))
 elif user_calc == "circle":
  radius = float(input("Give the radius: "))
  print("Area: ",calc_circle(radius))
 elif user_calc == "trapezoid":
  short_base = float(input("Give the length of the short base: "))
  long_base = float(input("Give the length of the long base: "))
  height = float(input("Give the height: "))
  print("Area: ",calc_trapezoid(short_base, long_base, height))
 else:
  area_calc_logic(input("Error, Re-enter input: "))
# if __name__ == '__main__':
print("This program will calculate/narea of some geometric shapes for you")
print( "Enter Square, Rectangle, Triangle, Circle, or Trapezoid")
shape=(input("What area would you like to calculate? ")).lower()
area_calc_logic(shape)

This program will calculate/narea of some geometric shapes for you
Enter Square, Rectangle, Triangle, Circle, or Trapezoid
What area would you like to calculate? Trapezoid
Give the length of the short base: 4
Give the length of the long base: 6
Give the height: 3
Area:  15.0


In [50]:
try:
 a = int(input("Enter numerator number: "))
 b = int(input("Enter denominator number: "))
 print("Result of Division: " + str(a/b))
except(ZeroDivisionError):
 print("You have divided a number by zero, which is not allowed.")
except(ValueError):
 print("You must enter integer value")
except:
 print("Oops! Something went wrong!")

Enter numerator number: 4
Enter denominator number: 0
You have divided a number by zero, which is not allowed.


In [70]:
result = []
name = 'anscombe.json'
for root, dirs, files in os.walk('/content'):
  print(dirs,files)
  if name in files:
    result.append(os.path.join(root, name))

['.config', 'sample_data'] []
['logs', 'configurations'] ['config_sentinel', '.last_update_check.json', '.last_opt_in_prompt.yaml', '.last_survey_prompt.yaml', 'gce', 'active_config']
['2021.11.18'] []
[] ['14.34.49.152157.log', '14.35.09.738473.log', '14.35.29.959577.log', '14.35.36.918574.log', '14.35.58.667492.log', '14.35.57.849518.log']
[] ['config_default']
[] ['anscombe.json', 'README.md', 'california_housing_train.csv', 'mnist_train_small.csv', 'mnist_test.csv', 'california_housing_test.csv']


In [3]:
import os

In [1]:
def find_all(name, path):
  result = []
  for root, dirs, files in os.walk(path):
    if name in files:
      result.append(os.path.join(root, name))
    # else:
      # raise FileNotPresent
      return result

In [4]:
fname = input("Enter the file name: ")
fpath = input("Enter path to search: ")
find_all(fname,fpath)

Enter the file name: anscombe.json
Enter path to search: /content


['/content/sample_data/anscombe.json']

In [ ]:
import os
class Error(Exception):
 """Base class for other exceptions"""
 pass
class FileNotPresent(Error):
 """Base class for other exceptions"""
 pass
try:
 def find_all(name, path):
  result = []
  for root, dirs, files in os.walk(path):
    if name in files:
      result.append(os.path.join(root, name))
    #   return result
    # else:
    #   raise FileNotPresent

except(FileNotPresent):
    print("File NOT present")
 
fname = input("Enter the file name: ")
fpath = input("Enter path to search: ")
find_all(fname,fpath)

In [ ]:
/content/sample_data/anscombe.json

In [ ]:
import re
mac= input("Enter a MAC address: ")
if re.search("^[a-fA-F0-9:]{17}|[a-fA-F0-9]{12}$", mac):
 print("Valid MAC address")
else:
 print("Not valid address")

In [ ]:

def max_of_two( x, y ):
 if x > y:
 return x
 return y
def max_of_three( x, y, z ):
 return max_of_two( x, max_of_two( y, z ) )
n= int(input("Enter no. of digits to compare: "))
if n==2:
 x=int(input("Enter first number: "))
 y=int(input("Enter second number: "))
 print(max_of_two(x,y))
elif n==3:
 x=int(input("Enter first number: "))
 y=int(input("Enter second number: "))
 z=int(input("Enter third number: "))
 print(max_of_three(x,y,z))
else:
 print("Enter a smaller value of N!")

In [ ]:
import math
degree = float(input("Input degrees: "))
radian = degree*(math.pi/180)
print("Radian value is: ",radian)

In [ ]:
import string, sys
def ispangram(str1, alphabet=string.ascii_lowercase):
 alphaset = set(alphabet)
 return alphaset <= set(str1.lower())
pan=input("Enter a sentence: ")
print ( ispangram(pan))

In [ ]:
class py_Roman:
 def int_to_Roman(self, num):
 val = [
 1000, 900, 500, 400,
 100, 90, 50, 40,
 10, 9, 5, 4,
 1
 ]
 syb = [
 "M", "CM", "D", "CD",
 "C", "XC", "L", "XL",
 "X", "IX", "V", "IV",
 "I"
 ]
 roman_num = ''
 i = 0
 while num > 0:
 for _ in range(num // val[i]):
 roman_num += syb[i]
 num -= val[i]
 i += 1
 return roman_num
num= int(input("Enter a number: "))
print("Roman numeral: ",py_Roman().int_to_Roman(num))

In [ ]:
class py_solution:
 def twoSum(self, nums, target):
 lookup = {}
 for i, num in enumerate(nums):
 if target - num in lookup:
 return (lookup[target - num], i )
 lookup[num] = i
 
target=int(input("Enter target sum: ")) 
print("index1=%d, index2=%d" % py_solution().twoSum((10,20,10,40,50,60,70),target))
inst=input("Enter instance: ")
inst.__class__.__name__

In [ ]:
def discriminant():
 x_value = float(input('The x value: '))
 y_value = float(input('The y value: '))
 z_value = float(input('The z value: '))
 discriminant = (y_value**2) - (4*x_value*z_value)
 if discriminant > 0:
 print('Two Solutions. Discriminant value is:', discriminant)
 elif discriminant == 0:
 print('One Solution. Discriminant value is:', discriminant)
 elif discriminant < 0:
 print('No Real Solutions. Discriminant value is:', discriminant)
discriminant()
def abc():
 x = 1
 y = 2
 str1= "This is a test example."
 print("Python Exercises")
print(abc.__code__.co_nlocals)

In [ ]:
import os, time
def last_modified_fileinfo(filepath):
 filestat = os.stat(filepath)
 date = time.localtime((filestat.st_mtime))
 # Extract year, month and day from the date
 year = date[0]
 month = date[1]
 day = date[2]
 # Extract hour, minute, second
 hour = date[3]
 minute = date[4]
 second = date[5]
 # Year
 strYear = str(year)[0:]
 # Month
 if (month <=9):
 strMonth = '0' + str(month)
 else:
 strMonth = str(month)
 # Date
 if (day <=9):
 strDay = '0' + str(day)
 else:
 strDay = str(day)
 return (strYear+"-"+strMonth+"-"+strDay+" "+str(hour)+":"+str(minute)+":"+str(second))
print()
print(last_modified_fileinfo('878_m4_slides_v1.0.pptx'))
# Enter a file present in the same folder, else mention the absolute path.
print()

In [ ]:
import calendar
cal = calendar.TextCalendar(calendar.SUNDAY)
# column width: 2, lines per week: 1 
# number of spaces between month columns: 1
# 3: no. of months per column.
year=int(input("Enter the year: "))
print(cal.formatyear(year, 2, 1, 1, 3))

In [ ]:
def toString(List): 
 return ''.join(List) 
# Function to print permutations of string 
# This function takes three parameters: 
# 1. String 
# 2. Starting index of the string 
# 3. Ending index of the string. 
def permute(a, l, r): 
 if l == r: 
 print(toString(a)) 
 else: 
 for i in range(l, r + 1): 
 a[l], a[i] = a[i], a[l] 
 permute(a, l + 1, r) 
 a[l], a[i] = a[i], a[l] # backtrack 
 
string = input("Enter a string: ")
n = len(string) 
a = list(string) 
permute(a, 0, n-1) 

In [ ]:
import random
def new_deck():
 """
 create a deck of cards
 suit: club=C, diamond=D, heart=H spade=S
 rank: ace=A, 10=T, jack=J, queen=Q, king=K, numbers=2..9
 ace of spade would be AS, 8 of heart would be 8H and so on
 return a list of a full deck of cards
 """
 rs = [rank + suit for rank in "A23456789TJQK" for suit in "CDHS"]
 return rs
def draw_cards(n, cards_list):
 """
 randomly draw n cards from the deck (cards_list)
 remove those cards from the deck
 since object cards_list is by reference, it will change too
 return a list of n cards
 """
 random.shuffle(cards_list)
 return [cards_list.pop() for k in range(n)]
# new deck
cards_list = new_deck()
print("New deck = %s cards" % len(cards_list)) # test
# draw n cards per hand
n = 5
# draw the hands
hand1 = draw_cards(n, cards_list)
hand2 = draw_cards(n, cards_list)
print('-'*40)
# show the 2 hands
print("hand1 = %s" % hand1)
print("hand2 = %s" % hand2)
print('-'*40)
print("New deck = %s cards" % len(cards_list)) # test
class Square:
 def square(num):
 return num ** 2
n=int(input("Enter number: ")) 
sq=Square.square(n)
print("Square of number is: ",sq)

In [ ]:
class India(): 
 def capital(self): 
 print("New Delhi is the capital of India.") 
 
 def language(self): 
 print("Hindi the primary language of India.") 
 
 def type(self): 
 print("India is a developing country.") 
 
class USA(): 
 def capital(self): 
 print("Washington, D.C. is the capital of USA.") 
 
 def language(self): 
 print("English is the primary language of USA.") 
 
 def type(self): 
 print("USA is a developed country.") 
 
def func(obj): 
 obj.capital() 
 obj.language() 
 obj.type() 
 
obj_ind = India() 
obj_usa = USA() 
 
func(obj_ind) 
func(obj_usa) 

In [ ]:
import random
answers = ['It is certain', 'It is decidedly so', 'Without a doubt', 'Yes – definitely', 'Y
print('Hello World, I am the Magic 8 Ball, What is your name?')
name = input()
print('Hello ' + name)
def Magic8Ball():
 print('Ask me a question.')
 input()
 print (answers[random.randint(0, len(answers)-1)] )
 print('I hope that helped!')
 Replay()
 
def Replay():
 print ('Do you have another question? [Y/N] ')
 reply = input()
 if reply == 'Y':
 Magic8Ball()
 elif reply == 'N':
 print("Adios!")
 exit()
 else:
 print('I apologies, I did not catch that. Please repeat.')
 Replay()
Magic8Ball()

In [ ]:
class Solution(object):
# DFS: iterative implement.
 def is_additive_number(self, num):
 length = len(num)
 for i in range(1, int(length/2+1)):
 for j in range(1, int((length-i)/2 + 1)):
 first, second, others = num[:i], num[i:i+j], num[i+j:]
 if self.isValid(first, second, others):
 return True
 return False
 def isValid(self, first, second, others):
 if ((len(first) > 1 and first[0] == "0") or
 (len(second) > 1 and second[0] == "0")):
 return False
 sum_str = str(int(first) + int(second))
 if sum_str == others:
 return True
 elif others.startswith(sum_str):
 return self.isValid(second, sum_str, others[len(sum_str):])
 else:
 return False
if __name__ == "__main__":
 seq=input("Enter Sequence: ")
 print(Solution().is_additive_number(seq))


In [ ]:
class employee:
 num_employee=0
 raise_amount=1.04
 def __init__(self, first, last, sal):
 self.first=first
 self.last=last
 self.sal=sal
 self.email=first + '.' + last + '@company.com'
 employee.num_employee+=1
 def fullname (self):
 return '{} {}'.format(self.first, self.last)
 def apply_raise (self):
 self.sal=int(self.sal* raise_amount)
class developer(employee):
 raise_amount = 1.10
 def __init__(self, first, last, sal, prog_lang):
 super().__init__(first, last, sal)
 self.prog_lang=prog_lang
 
class sales(employee):
 raise_amount = 1.01
 def __init__(self, first, last, sal, course_assign):
 super().__init__(first, last, sal)
 self.course_assign=course_assign
emp_1=developer('Guido', 'van Rossum', 1000000, 'Python')
emp_2=developer('Ani', 'Sri', 10000, 'Hadoop')
print(emp_1.prog_lang)
print(emp_2.sal)
print(emp_2.fullname)

In [ ]:
from abc import ABC, abstractmethod
class Polygon(ABC): 
 # abstract method 
 def noofsides(self): 
 pass
class Triangle(Polygon): 
 # overriding abstract method 
 def noofsides(self): 
 print("I have 3 sides") 
class Pentagon(Polygon): 
 # overriding abstract method 
 def noofsides(self): 
 print("I have 5 sides") 
class Hexagon(Polygon): 
 # overriding abstract method 
 def noofsides(self): 
 print("I have 6 sides") 
class Quadrilateral(Polygon): 
 # overriding abstract method 
 def noofsides(self): 
 print("I have 4 sides") 
# Driver code 
R = Triangle() 
R.noofsides() 
K = Quadrilateral() 
K.noofsides() 
R = Pentagon() 
R.noofsides() 
K = Hexagon() 
K.noofsides() 

In [52]:
class py_solution:
 def pow(self, x, n):
  if x==0 or x==1 or n==1:
    return x
    if x==-1:
      if n%2 ==0:
        return 1
      else:
        return -1
    if n==0:
      return 1
    if n<0:
      return 1/self.pow(x,-n)
  val = self.pow(x,n//2)
  if n%2 ==0:
  return val*val
  return val*val*x
print(py_solution().pow(2, -3));
print(py_solution().pow(3, 5));
print(py_solution().pow(100, 0));

IndentationError: ignored

In [50]:
def add(x, y):
 return x + y
# This function subtracts two numbers 
def subtract(x, y):
 return x - y
# This function multiplies two numbers
def multiply(x, y):
 return x * y
# This function divides two numbers
def divide(x, y):
 return x / y
print("Select operation.")
print("1.Add")
print("2.Subtract")
print("3.Multiply")
print("4.Divide")
# Take input from the user 
choice = input("Enter choice(1/2/3/4):")
num1 = int(input("Enter first number: "))
num2 = int(input("Enter second number: "))
if choice == '1':
 print(num1,"+",num2,"=", add(num1,num2))
elif choice == '2':
 print(num1,"-",num2,"=", subtract(num1,num2))
elif choice == '3':
 print(num1,"*",num2,"=", multiply(num1,num2))
elif choice == '4':
 print(num1,"/",num2,"=", divide(num1,num2))
else:
 print("Invalid input")
class IOString():
 def __init__(self):
  self.str1 = ""
 def get_String(self):
  self.str1 = input()
 def print_String(self):
  print(self.str1.upper())
str1 = IOString()
str1.get_String()
str1.print_String()

Select operation.
1.Add
2.Subtract
3.Multiply
4.Divide
Enter choice(1/2/3/4):3
Enter first number: 2
Enter second number: 5
2 * 5 = 10
t
T


In [48]:
import numpy as np
 
# input two matrices 
mat1 = ([1, 6, 5],[3 ,4, 8],[2, 12, 3]) 
mat2 = ([3, 4, 6],[5, 6, 7],[6,56, 7]) 
# This will return dot product 
res = np.dot(mat1,mat2) 
print(res) 

[[ 63 320  83]
 [ 77 484 102]
 [ 84 248 117]]


In [47]:
import numpy as np
x = np.array([-1.6, -1.5, -0.3, 0.1, 1.4, 1.8, 2.0])
print("Original array:")
print(x)
print("Floor values of the above array elements:")
print(np.floor(x))
print("Ceiling values of the above array elements:")
print(np.ceil(x))
print("Truncated values of the above array elements:")
print(np.trunc(x))
import numpy as np
arr = np.array([[2,3],[4,5]])
try:
 inverse = np.linalg.inv(arr)
 print(inverse)
except numpy.linalg.LinAlgError:
 # Not invertible. Skip this one.
 pass

Original array:
[-1.6 -1.5 -0.3  0.1  1.4  1.8  2. ]
Floor values of the above array elements:
[-2. -2. -1.  0.  1.  1.  2.]
Ceiling values of the above array elements:
[-1. -1. -0.  1.  2.  2.  2.]
Truncated values of the above array elements:
[-1. -1. -0.  0.  1.  1.  2.]
[[-2.5  1.5]
 [ 2.  -1. ]]


In [46]:
from numpy.polynomial import polynomial as P
x = (10,20,30)
y = (30,40,50)
print("Addition:")
print(P.polyadd(x,y))
print("Subtraction:")
print(P.polysub(x,y))
print("Multiplication:")
print(P.polymul(x,y))
print("Division:")
print(P.polydiv(x,y))

Addition:
[40. 60. 80.]
Subtraction:
[-20. -20. -20.]
Multiplication:
[ 300. 1000. 2200. 2200. 1500.]
Division:
(array([0.6]), array([-8., -4.]))


In [45]:
import numpy as np
n=int(input("Enter a number: "))
x = np.random.randn(n)
print("Average of the array elements:")
mean = x.mean()
print("\t",mean)
print("Standard deviation of the array elements:")
std = x.std()
print("\t",std)
print("Variance of the array elements:")
var = x.var()
print("\t",var)

Enter a number: 4
Average of the array elements:
	 0.4147999489512975
Standard deviation of the array elements:
	 1.6961288609114817
Variance of the array elements:
	 2.876853112816881


In [44]:
import numpy as np
x = np.array([1., 2., 0.4, .3])
print("Original array: ")
print(x)
r1 = np.reciprocal(x)
r2 = 1/x
assert np.array_equal(r1, r2)
print("Reciprocal for all elements of the said array:")
print(r1)

Original array: 
[1.  2.  0.4 0.3]
Reciprocal for all elements of the said array:
[1.         0.5        2.5        3.33333333]


In [43]:
import numpy as np
nums = np.random.rand(10)
print("Original array:")
print(nums)
n= int(input("Enter the number: "))
print("\nSorted first N elements:")
print(nums[np.argpartition(nums,range(n))])

Original array:
[0.25731416 0.04042978 0.11844027 0.04473193 0.39676445 0.49947563
 0.20289431 0.51452385 0.71297397 0.44470982]
Enter the number: 4

Sorted first N elements:
[0.04042978 0.04473193 0.11844027 0.20289431 0.39676445 0.49947563
 0.25731416 0.51452385 0.71297397 0.44470982]


In [42]:
import numpy as np
n=int(input("Enter number: "))
x = np.random.normal(size=n)
print(x)

Entyer number: 4
[ 0.85600904  0.78404864 -1.78924014  0.48208379]


In [41]:
# 11. Write a Python program to convert cartesian
# coordinates to polar coordinates of a random MxN
# matrix representing cartesian coordinates.

import numpy as np
x = np.random.randint(0, 10, 40)
print("Original array:")
print(x)
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())
import numpy as np
m=int(input("Enter no. of rows: "))
n=int(input("Enter no. of columns: "))
z= np.random.random((m,n))
x,y = z[:,0], z[:,1]
r = np.sqrt(x**2+y**2)
t = np.arctan2(y,x)
print("Cartesian Product: \n",r)
print("Polar Product: \n",t)

Original array:
[1 0 4 3 5 8 6 3 3 4 9 0 2 0 4 5 0 4 3 6 0 9 5 2 0 5 4 8 6 7 0 5 5 5 2 3 4
 2 0 8]
Most frequent value in the above array:
0
Enter no. of rows: 3
Enter no. of columns: 4
Cartesian Product: 
 [1.18494253 0.68564543 0.76299511]
Polar Product: 
 [0.69029258 0.8029805  0.68549593]


In [40]:
12. Write a Python program to shuffle numbers between X and Y.
import numpy as np
x=int(input("Lower limit: "))
y=int(input("Upper limit: "))
s = np.arange(x,y,0.5)
np.random.shuffle(s)
print(s)
print("Same result using permutation():")
print(np.random.permutation((y-x)))

Lower limit: 1
Upper limit: 4
[3.  1.5 2.  3.5 2.5 1. ]
Same result using permutation():
[0 2 1]


In [38]:
import numpy as np
x = np.random.random((3,3,3))
print(x)

[[[0.07703127 0.86911801 0.9003327 ]
  [0.52837712 0.5634075  0.87419228]
  [0.00343697 0.10480966 0.53433252]]

 [[0.98047993 0.26097643 0.75515696]
  [0.9835696  0.64334477 0.89493745]
  [0.26165312 0.33599652 0.4914245 ]]

 [[0.0124988  0.61325732 0.44752078]
  [0.74721552 0.89529292 0.817164  ]
  [0.9085243  0.79908483 0.49179294]]]


In [37]:
# 14. Write a Python program to find point by point
# distances of a random vector with shape (J,K) representing coordinates.
import numpy as np
j=int(input("Enter J: "))
k=int(input("Enter K: "))
a= np.random.random((j,k))
x,y = np.atleast_2d(a[:,0], a[:,1])
d = np.sqrt( (x-x.T)**2 + (y-y.T)**2)
print(d)

Enter J: 3
Enter K: 4
[[0.         0.3479793  0.55256527]
 [0.3479793  0.         0.83331039]
 [0.55256527 0.83331039 0.        ]]


In [ ]:
import numpy as np
data = [20.0497520, 31.39864012947, 12.30974023]

In [36]:
import numpy as np
x = np.array(['Python', 'PHP', 'JS', 'Examples', 'html5', '5'], dtype=np.str)
print("\nOriginal Array:")
print(x,"\n")
r1 = np.char.isdigit(x)
r2 = np.char.islower(x)
r3 = np.char.isupper(x)
print("Digits only =", r1)
print("Lower cases only =", r2)
print("Upper cases only =", r3)



Original Array:
['Python' 'PHP' 'JS' 'Examples' 'html5' '5'] 

Digits only = [False False False False False  True]
Lower cases only = [False False False False  True False]
Upper cases only = [False  True  True False False False]


In [35]:
import numpy as np
a = np.array([1,2,3])
b = np.array([0,1,0])
print("Original 1-d arrays:")
print(a)
print(b)
result = np.einsum("n,n", a, b)
print("Einstein’s summation convention of the said arrays:")
print(result)
x = np.arange(9).reshape(3, 3)
y = np.arange(3, 12).reshape(3, 3)
print("Original Higher dimension:")
print(x)
print(y)
result = np.einsum("mk,kn", x, y)
print("Einstein’s summation convention of the said arrays:")
print(result)

Original 1-d arrays:
[1 2 3]
[0 1 0]
Einstein’s summation convention of the said arrays:
2
Original Higher dimension:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Einstein’s summation convention of the said arrays:
[[ 24  27  30]
 [ 78  90 102]
 [132 153 174]]


In [34]:
import numpy
A = numpy.matrix([[1,3,7],[2,8,3],[7,8,1]])
numpy.linalg.matrix_rank(A)

# HINT: In the field of numerical analysis, the condition number of a function with respect to an argument
# measures how much the output value of the function can change for a small change in the input
# argument. This is used to measure how sensitive a function is to changes or errors in the input, and
# how much error in the output results from an error in the input.

3

In [33]:
import numpy as np
m = np.array([[1,2],[3,4]])
print("Original matrix:")
print(m)
result = np.linalg.cond(m)
print("Condition number of the said matrix:")
print(result)

Original matrix:
[[1 2]
 [3 4]]
Condition number of the said matrix:
14.933034373659265


In [32]:
import numpy as np
m=int(input("Enter value M: "))
n=int(input("Enter value N: "))
a=int(input("Enter value A: "))
x = np.random.random((m,n))
print("First array:")
print(x)
y = np.random.random((n,a))
print("Second array:")
print(y)
z = np.dot(x, y)
print("Dot product of two arrays:")
print(z)

Enter value M: 3
Enter value N: 4
Enter value A: 2
First array:
[[0.32960768 0.47523112 0.57443577 0.09162582]
 [0.25809263 0.63688383 0.59570488 0.93580438]
 [0.79991909 0.47129729 0.27033741 0.86652055]]
Second array:
[[0.92069541 0.04604604]
 [0.10363419 0.49833643]
 [0.29875093 0.86193905]
 [0.44976357 0.43872845]]
Dot product of two arrays:
[[0.56554164 0.78732958]
 [0.90248574 1.25329186]
 [1.25581727 0.8848793 ]]


In [31]:
import pandas
listx = [10, 20, 30, 40]
table = pandas.DataFrame(listx)
print("List to dataframes")
print(table)
print()
data = [{'a':1, 'b':2}, {'a':2, 'b':4, 'c':8}]
table = pandas.DataFrame(data)
print("Dictionaries to Dataframe")
print(table)
print()
data = [{'a':1, 'b':2}, {'a':2, 'b':4, 'c':8}]
table = pandas.DataFrame(data, index=[ 'first', 'second' ])
print("List of Dictionaries to dataframe")
print(table)
print()
data = {'one': pandas.Series([1, 2, 3], index=['a', 'b', 'c']),'two': pandas.Series([1, 2, 3], index=['a', 'b', 'c'])}
table = pandas.DataFrame(data)
print("Dictionary of series to Dataframe")
print(table)
print()

List to dataframes
    0
0  10
1  20
2  30
3  40

Dictionaries to Dataframe
   a  b    c
0  1  2  NaN
1  2  4  8.0

List of Dictionaries to dataframe
        a  b    c
first   1  2  NaN
second  2  4  8.0

Dictionary of series to Dataframe
   one  two
a    1    1
b    2    2
c    3    3



In [29]:
import numpy as np
import pandas as pd
np_array = np.array([10, 20, 30, 40, 50])
print("NumPy array:")
print(np_array)
print()
new_series = pd.Series(np_array)
print("Converted Pandas series:")
print(new_series)

NumPy array:
[10 20 30 40 50]

Converted Pandas series:
0    10
1    20
2    30
3    40
4    50
dtype: int64


In [28]:
import pandas
data = {'one': pandas.Series([1, 2, 3], index=['a', 'b', 'c']),
 'two': pandas.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])}
table = pandas.DataFrame(data)
print("Before adding a column: ")
print(table)
print()
table['three'] = pandas.Series([10, 20, 30], index=['a', 'b', 'c'])
print("After adding a column: ")
print(table)
print()
print("Deleting column three: ")
del table['three']
print(table)
print()
print("Deleting column one: ")
table.pop('one')
print(table)

Before adding a column: 
   one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  NaN    4

After adding a column: 
   one  two  three
a  1.0    1   10.0
b  2.0    2   20.0
c  3.0    3   30.0
d  NaN    4    NaN

Deleting column three: 
   one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  NaN    4

Deleting column one: 
   two
a    1
b    2
c    3
d    4


In [27]:
import pandas
data = {'one': pandas.Series([1, 2, 3], index=['a', 'b', 'c']),
 'two': pandas.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])}
table = pandas.DataFrame(data)
table['three'] = pandas.Series([10, 20, 30], index=['a', 'b', 'c'])
print(table)
print()
row = pandas.DataFrame([[11, 13], [17, 19]], columns=['two', 'three'])
table = table.append(row, ignore_index=True)
print(table)
print()
r=int(input("Enter Row no. to drop: "))
table = table.drop(r)
print(table)

   one  two  three
a  1.0    1   10.0
b  2.0    2   20.0
c  3.0    3   30.0
d  NaN    4    NaN

   one  two  three
0  1.0    1   10.0
1  2.0    2   20.0
2  3.0    3   30.0
3  NaN    4    NaN
4  NaN   11   13.0
5  NaN   17   19.0

Enter Row no. to drop: 5
   one  two  three
0  1.0    1   10.0
1  2.0    2   20.0
2  3.0    3   30.0
3  NaN    4    NaN
4  NaN   11   13.0


In [26]:
import json
import csv
employee_data = '{"employee_details":[{"employee_name": "James", "email": "james@gmail.com"}]}'
employee_parsed = json.loads(employee_data)
emp_data = employee_parsed['employee_details']
# open a file for writing
employ_data = open('EmployeeData.csv', 'w')
# create the csv writer object
csvwriter = csv.writer(employ_data)
count = 0
for emp in emp_data:
 if count == 0:
  header = emp.keys()
  csvwriter.writerow(header)
  count += 1
  csvwriter.writerow(emp.values())
employ_data.close()
print("DONE")

DONE


In [22]:
import pandas as pd
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 9])
ds = ds1 + ds2
print("Add two Series:")
print(ds)
print()
print("Subtract two Series:")
ds = ds1 - ds2
print(ds)
print()
print("Multiply two Series:")
ds = ds1 * ds2
print(ds)
print()
print("Divide Series1 by Series2:")
ds = ds1 / ds2
print(ds)
print()

Add two Series:
0     3
1     7
2    11
3    15
4    19
dtype: int64

Subtract two Series:
0    1
1    1
2    1
3    1
4    1
dtype: int64

Multiply two Series:
0     2
1    12
2    30
3    56
4    90
dtype: int64

Divide Series1 by Series2:
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64



In [21]:
import pandas as pd
s1 = pd.Series(['100', '200', 'python', '300.12', '400'])
print("Original Data Series:")
print(s1)
print()
print("Change the said data type to numeric:")
s2 = pd.to_numeric(s1, errors='coerce')
print(s2)

Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object

Change the said data type to numeric:
0    100.00
1    200.00
2       NaN
3    300.12
4    400.00
dtype: float64


In [20]:
import pandas as pd
s = pd.Series([0, 1,2,3,4,5,6,7,8,9,10])
print("Original Data Series:")
print(s)
print("\nSubset of the above Data Series:")
n=int(input("Enter N: "))
new_s = s[s < n]
print(new_s)

Original Data Series:
0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
dtype: int64

Subset of the above Data Series:
Enter N: 5
0    0
1    1
2    2
3    3
4    4
dtype: int64


In [19]:
import pandas as pd
s = pd.Series(data = [1,2,3,4,5,6,7,8,9,5,3])
print("Original Data Series:")
print(s)
print("\nMean of the said Data Series:")
print(s.mean())
print("\nStandard deviation of the said Data Series:")
print(s.std())

Original Data Series:
0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9     5
10    3
dtype: int64

Mean of the said Data Series:
4.818181818181818

Standard deviation of the said Data Series:
2.522624895547565


In [18]:
import pandas as pd
s = pd.Series(data = [1,2,3,4,5], index = ['A', 'B', 'C','D','E'])
print("Original Data Series:")
print(s)
print()
s = s.reindex(index = ['B','A','C','D','E'])
print("Data Series after changing the order of index:")
print(s)

Original Data Series:
A    1
B    2
C    3
D    4
E    5
dtype: int64

Data Series after changing the order of index:
B    2
A    1
C    3
D    4
E    5
dtype: int64


In [17]:
import pandas as pd
import numpy as np
s1 = pd.Series(['100', '200', 'python', '300.12', '400'])
print("Original Data Series:")
print(s1)
print()
print("Series to an array")
a = np.array(s1.values.tolist())
print (a)

Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object

Series to an array
['100' '200' 'python' '300.12' '400']


In [16]:
import pandas as pd
s = pd.Series([
 ['Red', 'Green', 'White'],
 ['Red', 'Black'],
 ['Yellow']])
print("Original Series of list: ")
print(s)
print()
s = s.apply(pd.Series).stack().reset_index(drop=True)
print("One Series: ")
print(s)

Original Series of list: 
0    [Red, Green, White]
1           [Red, Black]
2               [Yellow]
dtype: object

One Series: 
0       Red
1     Green
2     White
3       Red
4     Black
5    Yellow
dtype: object


In [15]:
import pandas as pd
s = pd.Series(['100', '200', 'python', '300.12', '400'])
print("Original Data Series:")
print(s)
print()
new_s = pd.Series(s).sort_values()
print("Sorted series: ")
print(new_s)

Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object

Sorted series: 
0       100
1       200
3    300.12
4       400
2    python
dtype: object


In [14]:
import numpy as np
 
# input two matrices 
mat1 = ([1, 6, 5],[3 ,4, 8],[2, 12, 3]) 
mat2 = ([3, 4, 6],[5, 6, 7],[6,56, 7]) 
# This will return dot product 
res = np.dot(mat1,mat2) 
print(res) 

[[ 63 320  83]
 [ 77 484 102]
 [ 84 248 117]]


In [13]:
import pandas as pd
import numpy as np
import datetime
dat=input("Enter date in YYYY-MM-DD HH:MM:SS format: ")
prd=int(input("Period of years: "))
date1 = pd.Series(pd.date_range(dat, periods=prd, freq='Y'))
df = pd.DataFrame(dict(date_given=date1))
print(df)
df['Is_leap_year'] = df['date_given'].dt.is_leap_year
print(df)

Enter date in YYYY-MM-DD HH:MM:SS format: 2000-12-12 12:12:23
Period of years: 4
           date_given
0 2000-12-31 12:12:23
1 2001-12-31 12:12:23
2 2002-12-31 12:12:23
3 2003-12-31 12:12:23
           date_given  Is_leap_year
0 2000-12-31 12:12:23          True
1 2001-12-31 12:12:23         False
2 2002-12-31 12:12:23         False
3 2003-12-31 12:12:23         False


In [12]:
import pandas as pd
import numpy as np
#Create a DataFrame
df1 = {
 'Name':['George','Andrea','micheal','maggie','Ravi','Xien','Jalpa'],
 'University_Rank':[6,47,21,74,32,77,8]}
df1 = pd.DataFrame(df1,columns=['Name','University_Rank'])
print(df1)
print()
df1['log_value'] = np.log(df1['University_Rank'])
df1['log2_value'] = np.log2(df1['University_Rank'])
df1['log10_value'] = np.log10(df1['University_Rank'])
print(df1)

      Name  University_Rank
0   George                6
1   Andrea               47
2  micheal               21
3   maggie               74
4     Ravi               32
5     Xien               77
6    Jalpa                8

      Name  University_Rank  log_value  log2_value  log10_value
0   George                6   1.791759    2.584963     0.778151
1   Andrea               47   3.850148    5.554589     1.672098
2  micheal               21   3.044522    4.392317     1.322219
3   maggie               74   4.304065    6.209453     1.869232
4     Ravi               32   3.465736    5.000000     1.505150
5     Xien               77   4.343805    6.266787     1.886491
6    Jalpa                8   2.079442    3.000000     0.903090


In [11]:
import pandas as pd
import numpy as np
import datetime
from dateutil.relativedelta import relativedelta
from datetime import date
date1 = pd.Series(pd.date_range('2012-1-1 12:00:00', periods=7, freq='M'))
date2 = pd.Series(pd.date_range('2013-3-11 21:45:00', periods=7, freq='W'))
df = pd.DataFrame(dict(Start_date = date1, End_date = date2))
print(df)
print()
#Difference in seconds
df['diff_seconds'] = df['End_date'] - df['Start_date']
df['diff_seconds']=df['diff_seconds']/np.timedelta64(1,'s')
#Difference in minutes
df['diff_minutes'] = df['End_date'] - df['Start_date']
df['diff_minutes']=df['diff_minutes']/np.timedelta64(1,'m')
#Difference in Hours
df['diff_hours'] = df['End_date'] - df['Start_date']
df['diff_hours']=df['diff_hours']/np.timedelta64(1,'h')
#Difference in Nanoseconds
df['diff_nano_seconds'] = df['End_date'] - df['Start_date']
df['diff_nano_seconds']=df['diff_nano_seconds']/np.timedelta64(1,'ns')
print(df)

           Start_date            End_date
0 2012-01-31 12:00:00 2013-03-17 21:45:00
1 2012-02-29 12:00:00 2013-03-24 21:45:00
2 2012-03-31 12:00:00 2013-03-31 21:45:00
3 2012-04-30 12:00:00 2013-04-07 21:45:00
4 2012-05-31 12:00:00 2013-04-14 21:45:00
5 2012-06-30 12:00:00 2013-04-21 21:45:00
6 2012-07-31 12:00:00 2013-04-28 21:45:00

           Start_date            End_date  ...  diff_hours  diff_nano_seconds
0 2012-01-31 12:00:00 2013-03-17 21:45:00  ...     9873.75       3.554550e+16
1 2012-02-29 12:00:00 2013-03-24 21:45:00  ...     9345.75       3.364470e+16
2 2012-03-31 12:00:00 2013-03-31 21:45:00  ...     8769.75       3.157110e+16
3 2012-04-30 12:00:00 2013-04-07 21:45:00  ...     8217.75       2.958390e+16
4 2012-05-31 12:00:00 2013-04-14 21:45:00  ...     7641.75       2.751030e+16
5 2012-06-30 12:00:00 2013-04-21 21:45:00  ...     7089.75       2.552310e+16
6 2012-07-31 12:00:00 2013-04-28 21:45:00  ...     6513.75       2.344950e+16

[7 rows x 6 columns]


In [10]:
import numpy as np
n = int(input("Enter value of N: "))
x = np.random.random(n)
print("Original array:")
print(x)
x[x.argmax()] = n
print("Maximum value replaced by -1:")
print(x)

Enter value of N: 6
Original array:
[0.61722395 0.80349646 0.68131463 0.93929451 0.42665948 0.65486627]
Maximum value replaced by -1:
[0.61722395 0.80349646 0.68131463 6.         0.42665948 0.65486627]


In [9]:
import pandas as pd
import numpy as np
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matt', 'Asf','Gff','Uhg'],
 'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
 'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
 'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(exam_data , index=labels)
print("Orginal rows:")
print(df)
print()
nm1=input("Enter Name to be replaced: ")
nm2=input("Enter new name: ")
print("\nChange the name %s to %s: ",nm1,nm2)
df['name'] = df['name'].replace(nm1, nm2)
print(df)

Orginal rows:
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g       Matt   14.5         1     yes
h        Asf    NaN         1      no
i        Gff    8.0         2      no
j        Uhg   19.0         1     yes

Enter Name to be replaced: Dima
Enter new name: Gd

Change the name %s to %s:  Dima Gd
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b         Gd    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g       Matt   14.5         1     yes
h        Asf    NaN         1      no
i        Gff    8.0         2      no
j        Uhg   19.0         1     yes


In [8]:
import numpy as np
x = np.array([' python exercises ', ' PHP ', ' java ', ' C++'], dtype=np.str)
print("Original Array:")
print(x)
stripped = np.char.strip(x)
print("\nRemove the leading and trailing whitespaces: ", stripped)

Original Array:
[' python exercises ' ' PHP ' ' java ' ' C++']

Remove the leading and trailing whitespaces:  ['python exercises' 'PHP' 'java' 'C++']
